scipost_django/api/urls.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.urls import include, path

from rest_framework import routers


# colleges
from colleges.api.viewsets import FellowshipPublicAPIViewSet

# journals
from journals.api.viewsets import (
    PublicationPublicAPIViewSet,
    PublicationPublicSearchAPIViewSet,
    PubFracPublicAPIViewSet,
)

# submissions
from submissions.api.viewsets import (
    SubmissionPublicAPIViewSet,
    SubmissionPublicSearchAPIViewSet,
)

# organizations
from organizations.api.viewsets import (
    OrganizationPublicAPIViewSet,
    OrganizationNAPViewSet,
)

# finances
from finances.api.viewsets import SubsidyFinAdminAPIViewSet, SubsidyPublicAPIViewSet


# Next two: old style, to be deprecated:
from conflicts.viewsets import ConflictOfInterestViewSet
from news.viewsets import NewsItemViewSet

# Utilities
from api.views.omniauth import OmniAuthUserInfoView
import api.views.search as search_views


app_name = "api"


router = routers.SimpleRouter()

# search (Vue-based) routes
router.register(
    "search/publications",
    PublicationPublicSearchAPIViewSet,
    basename="search_publications",
)
router.register(
    "search/submissions",
    SubmissionPublicSearchAPIViewSet,
    basename="search_submissions",
)

#############################
# publicly-accessible routes
#############################

# colleges
router.register("colleges/fellowships", FellowshipPublicAPIViewSet)


# journals
router.register("publications", PublicationPublicAPIViewSet)
router.register("pubfracs", PubFracPublicAPIViewSet)

# submissions
router.register("submissions", SubmissionPublicAPIViewSet)

# organizations
router.register("organizations", OrganizationPublicAPIViewSet)
router.register("nap", OrganizationNAPViewSet, basename="organization_nap")

# finances
router.register(
    "finadmin/subsidies", SubsidyFinAdminAPIViewSet, basename="subsidies_finadmin"
)
router.register("subsidies", SubsidyPublicAPIViewSet)

# Next two: old style, to be deprecated:
router.register(r"news", NewsItemViewSet)
router.register(r"conflicts", ConflictOfInterestViewSet)


urlpatterns = router.urls


urlpatterns += [
    path(  # /api/omniauth/userinfo/, for SciPost as GitLab/OmniAuth authorization server
        "omniauth/userinfo/", OmniAuthUserInfoView.as_view(), name="omniauth_userinfo"
    ),
    path(  # /api/available_search_tabs/
        "available_search_tabs/",
        search_views.available_search_tabs,
        name="available_search_tabs",
    ),
]

scipost_django/invitations/urls.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.urls import path

from . import views

app_name = "invitations"

urlpatterns = [
    path("", views.RegistrationInvitationsView.as_view(), name="list"),
    path("sent", views.RegistrationInvitationsSentView.as_view(), name="list_sent"),
    path(
        "contributors",
        views.RegistrationInvitationsDraftContributorView.as_view(),
        name="list_contributors",
    ),
    path(
        "fellows",
        views.RegistrationInvitationsFellowView.as_view(),
        name="list_fellows",
    ),
    path("new", views.create_registration_invitation_or_citation, name="new"),
    path("<int:pk>/", views.RegistrationInvitationsUpdateView.as_view(), name="update"),
    path(
        "<int:pk>/add_citation",
        views.RegistrationInvitationsAddCitationView.as_view(),
        name="add_citation",
    ),
    path(
        "<int:pk>/delete",
        views.RegistrationInvitationsDeleteView.as_view(),
        name="delete",
    ),
    path(
        "<int:pk>/merge", views.RegistrationInvitationsMergeView.as_view(), name="merge"
    ),
    path(
        "<int:pk>/mark/<str:label>",
        views.RegistrationInvitationsMarkView.as_view(),
        name="mark",
    ),
    path(
        "<int:pk>/map_to_contributor/<int:contributor_id>/",
        views.RegistrationInvitationsMapToContributorView.as_view(),
        name="map_to_contributor",
    ),
    path(
        "<int:pk>/send_reminder",
        views.RegistrationInvitationsReminderView.as_view(),
        name="send_reminder",
    ),
    path("cleanup", views.cleanup, name="cleanup"),
    path(
        "citations",
        views.CitationNotificationsView.as_view(),
        name="citation_notification_list",
    ),
    path(
        "citations/<int:pk>",
        views.CitationNotificationsProcessView.as_view(),
        name="citation_notification_process",
    ),
]

scipost_django/invitations/models.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


import datetime
import hashlib
import random
import string

from django.db import models, IntegrityError
from django.conf import settings
from django.utils import timezone

from . import constants
from .managers import RegistrationInvitationQuerySet, CitationNotificationQuerySet

from scipost.constants import TITLE_CHOICES


class RegistrationInvitation(models.Model):
    """
    Invitation to particular persons for registration
    """

    profile = models.ForeignKey(
        "profiles.Profile", on_delete=models.SET_NULL, blank=True, null=True
    )
    title = models.CharField(max_length=4, choices=TITLE_CHOICES)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.EmailField()
    status = models.CharField(
        max_length=8,
        choices=constants.REGISTATION_INVITATION_STATUSES,
        default=constants.STATUS_DRAFT,
    )

    # Text content
    message_style = models.CharField(
        max_length=1,
        choices=constants.INVITATION_STYLE,
        default=constants.INVITATION_FORMAL,
    )
    personal_message = models.TextField(blank=True)
    invited_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="invitations_sent",
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="invitations_created",
    )

    # Related to objects
    invitation_type = models.CharField(
        max_length=2,
        choices=constants.INVITATION_TYPE,
        default=constants.INVITATION_CONTRIBUTOR,
    )

    # Response keys
    invitation_key = models.CharField(max_length=40, unique=True)
    key_expires = models.DateTimeField(default=timezone.now)

    # Timestamps
    date_sent_first = models.DateTimeField(null=True, blank=True)
    date_sent_last = models.DateTimeField(null=True, blank=True)
    times_sent = models.PositiveSmallIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    objects = RegistrationInvitationQuerySet.as_manager()

    class Meta:
        ordering = ["last_name"]

    def __init__(self, *args, **kwargs):
        response = super().__init__(*args, **kwargs)
        self.refresh_keys()
        return response

    def __str__(self):
        return "{} {} on {}".format(
            self.first_name, self.last_name, self.created.strftime("%Y-%m-%d")
        )

    def refresh_keys(self, force_new_key=False):
        # Generate email activation key and link
        if not self.invitation_key or force_new_key:
            # TODO: Replace this all by the `secrets` package available from python 3.6(!)
            salt = ""
            for i in range(5):
                salt += random.choice(string.ascii_letters)
            salt = salt.encode("utf8")
            invitationsalt = self.last_name.encode("utf8")
            self.invitation_key = hashlib.sha1(salt + invitationsalt).hexdigest()
            self.key_expires = timezone.now() + datetime.timedelta(days=365)

    def mail_sent(self, user=None):
        """
        Update instance fields as if a new invitation mail has been sent out.
        """
        if self.status == constants.STATUS_DRAFT:
            self.status = constants.STATUS_SENT
        if not self.date_sent_first:
            self.date_sent_first = timezone.now()
        self.date_sent_last = timezone.now()
        self.invited_by = user or self.created_by
        self.times_sent += 1
        self.citation_notifications.update(processed=True)
        self.save()

    @property
    def has_responded(self):
        return self.status in [constants.STATUS_DECLINED, constants.STATUS_REGISTERED]


class CitationNotification(models.Model):
    invitation = models.ForeignKey(
        "invitations.RegistrationInvitation",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    contributor = models.ForeignKey(
        "scipost.Contributor",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="+",
    )

    # Content
    submission = models.ForeignKey(
        "submissions.Submission",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="+",
    )
    publication = models.ForeignKey(
        "journals.Publication",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="+",
    )
    processed = models.BooleanField(default=False)

    # Meta info
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="notifications_created",
    )
    date_sent = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    objects = CitationNotificationQuerySet.as_manager()

    class Meta:
        default_related_name = "citation_notifications"
        unique_together = (
            ("invitation", "submission"),
            ("invitation", "publication"),
            ("contributor", "submission"),
            ("contributor", "publication"),
        )

    def __str__(self):
        _str = "Citation for "
        if self.invitation:
            _str += " Invitation ({} {})".format(
                self.invitation.first_name,
                self.invitation.last_name,
            )
        elif self.contributor:
            _str += " Contributor ({})".format(self.contributor)

        _str += " on "
        if self.submission:
            _str += "Submission ({})".format(
                self.submission.preprint.identifier_w_vn_nr
            )
        elif self.publication:
            _str += "Publication ({})".format(self.publication.doi_label)
        return _str

    def save(self, *args, **kwargs):
        if not self.submission and not self.publication:
            raise IntegrityError(
                (
                    "CitationNotification needs to be related to either a "
                    "Submission or Publication object."
                )
            )
        return super().save(*args, **kwargs)

    def mail_sent(self):
        """
        Update instance fields as if a new citation notification mail has been sent out.
        """
        self.processed = True
        if not self.date_sent:
            # Don't overwrite by accident...
            self.date_sent = timezone.now()
        self.save()

    def related_notifications(self):
        return CitationNotification.objects.unprocessed().filter(
            models.Q(contributor=self.contributor)
            | models.Q(invitation=self.invitation)
        )

    def get_first_related_contributor(self):
        return self.related_notifications().filter(contributor__isnull=False).first()

    @property
    def email(self):
        if self.invitation:
            return self.invitation.email
        elif self.contributor:
            return self.contributor.user.email

    @property
    def last_name(self):
        if self.invitation:
            return self.invitation.last_name
        elif self.contributor:
            return self.contributor.user.last_name

    @property
    def get_title(self):
        if self.invitation:
            return self.invitation.get_title_display()
        elif self.contributor and self.contributor.profile:
            return self.contributor.profile.get_title_display()

scipost_django/invitations/templates/invitations/_citationnotification_table.html
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Type</th>
      <th>Cited in</th>
      <th>Created by</th>
      <th>Date created</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for notification in notifications %}
      <tr>
        <td>
          {% if notification.contributor %}
            {{ notification.contributor.user.first_name }} {{ notification.contributor.user.last_name }}
          {% elif notification.invitation %}
            {{ notification.invitation.first_name }} {{ notification.invitation.last_name }}
          {% endif %}
        </td>
        <td>
          {% if notification.contributor %}
            {{ notification.contributor.user.email }}
          {% elif notification.invitation %}
            {{ notification.invitation.email }}
          {% endif %}
        </td>
        <td>
          {% if notification.contributor %}For Contributor{% elif notification.invitation %}Registration Invitation{% else %}<span class="text-danger">Invalid</span>{% endif %}
        </td>
        <td>
          {% if notification.publication %}
            {{ notification.publication.citation }}
          {% endif %}
          {% if notification.submission %}
            {{ notification.submission.preprint.identifier_w_vn_nr }}
          {% endif %}
        </td>
        <td>{{ notification.created_by.first_name }} {{ notification.created_by.last_name }}</td>
        <td>{{ notification.created }}</td>
        <td>
          {% if notification.contributor %}
            <a href="{% url 'invitations:citation_notification_process' notification.id %}">Process citation</a>
          {% elif notification.invitation %}
            {% if notification.invitation.status == 'draft' %}
              <a href="{% url 'invitations:update' notification.invitation.id %}">Edit/send invitation</a>
            {% elif notification.invitation.status == 'send' or notification.invitation.status == 'edited' %}
              <a href="{% url 'invitations:send_reminder' notification.invitation.id %}">Send reminder</a>
            {% endif %}
          {% endif %}
        </td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="7">
          All Citation Notifications have been processed.
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

scipost_django/invitations/templates/invitations/_registrationinvitation_summary.html
<table class="registration_invitation">
  <tr>
    <th>Name</th>
    <td>{{ invitation.get_title_display }} {{ invitation.first_name }} {{ invitation.last_name }}</td>
  </tr>
  <tr>
    <th>Email</th>
    <td>{{ invitation.email }}</td>
  </tr>
  <tr>
    <th>Status</th>
    <td>{{ invitation.get_status_display }}</td>
  </tr>

  <tr>
    <th>Submission(s)</th>
    <td>
      <ul class="ps-3 mb-0">
        {% for citation in invitation.citation_notifications.for_submissions %}
          <li>{{ citation.submission }}</li>
        {% empty %}
          <li><em>No submissions linked</em></li>
        {% endfor %}
      </ul>
    </td>
  </tr>
  <tr>
    <th>Publication(s)</th>
    <td>
      <ul class="ps-3 mb-0">
        {% for citation in invitation.citation_notifications.for_publications %}
          <li>{{ citation.publication }}</li>
        {% empty %}
          <li><em>No publications linked</em></li>
        {% endfor %}
      </ul>
    </td>
  </tr>
  <tr>
    <th>Created</th>
    <td>{{ invitation.created }}</td>
  </tr>
  <tr>
    <th>Times sent</th>
    <td><strong>{{ invitation.times_sent }}</strong> time{{ invitation.times_sent|pluralize }}{% if invitation.times_sent %} (last time: {{ invitation.date_sent_last }}){% endif %}</td>
  </tr>
</table>

{% if invitation.personal_message %}
  <br>
  <strong>Personal Message</strong>
  <p>{{ invitation.personal_message|linebreaksbr }}</p>
{% endif %}

scipost_django/invitations/templates/invitations/citationnotification_list.html
{% extends 'scipost/_personal_page_base.html' %}

{% load bootstrap %}

{% block pagetitle %}: Unprocessed Citation Notifications{% endblock pagetitle %}

{% block breadcrumb_items %}
  {{block.super}}
  <a href="{% url 'invitations:list' %}" class="breadcrumb-item">Registration Invitations</a>
  <span class="breadcrumb-item">Unprocessed Citation Notifications</span>
{% endblock %}

{% block content %}

  <h1 class="highlight">Unprocessed Citation Notifications</h1>
  <a href="{% url 'invitations:list' %}">Back to Registration Invitations</a>

  <div class="row">
    <div class="col-12">
      <br>
      {% include 'invitations/_citationnotification_table.html' with notifications=object_list %}

      {% if is_paginated %}
	<div class="col-12">
	  {% include '_pagination.html' with page_obj=page_obj %}
	</div>
      {% endif %}
    </div>
  </div>

{% endblock %}

scipost_django/invitations/templates/invitations/registrationinvitation_cleanup.html
{% extends 'scipost/_personal_page_base.html' %}

{% block pagetitle %}: Registration Invitations cleanup{% endblock pagetitle %}


{% block breadcrumb_items %}
  {{ block.super }}
  <a href="{% url 'invitations:list' %}" class="breadcrumb-item">Registration Invitations</a>
  <span class="breadcrumb-item">Cleanup</span>
{% endblock %}

{% block content %}


  <div class="row">
    <div class="col-12">
      <h1 class="highlight">Registration Invitations Cleanup</h1>
      <h3>Email duplicates (a contributor exists with the email address in these invitations)</h3>
    </div>
  </div>


  <div class="row">
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th>Last name</th>
            <th>First name</th>
            <th>Email</th>
            <th>Date sent</th>
            <th>Type</th>
            <th>Invited by</th>
          </tr>
        </thead>
        <tbody>
          {% for inv in invitations %}
            <tr>
              <td>{{ inv.last_name }}</td>
              <td>{{ inv.first_name }}</td>
              <td>{{ inv.email }}</td>
              <td>{{ inv.date_sent_first }} </td>
              <td>{{ inv.get_invitation_type_display }}</td>
              <td>{{ inv.invited_by }}</td>
              <td><a href="{% url 'invitations:delete' inv.id %}">Remove</a></td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="7">There were no duplicate emails found in the sets of Contributors/Invitations.</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

{% endblock content %}

scipost_django/invitations/templates/invitations/registrationinvitation_confirm_delete.html
{% extends 'scipost/_personal_page_base.html' %}

{% block pagetitle %}: Delete Registration Invitation{% endblock pagetitle %}

{% block breadcrumb_items %}
  {{block.super}}
  <a href="{% url 'invitations:list' %}" class="breadcrumb-item">Registration Invitations</a>
  <span class="breadcrumb-item">Delete {{ object.id }}</span>
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-12">
      <h1 class="highlight">Delete Registration Invitation {{ object.id }}</h1>
      <p>Are you sure you want to delete the Registration Invitation?</p>
      {% include 'invitations/_registrationinvitation_summary.html' with invitation=object %}

      <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete Registration Invitation">
      </form>

    </div>
  </div>

{% endblock %}

scipost_django/invitations/templates/invitations/registrationinvitation_form_add_new.html
{% extends 'scipost/_personal_page_base.html' %}

{% block pagetitle %}: New Registration Invitation{% endblock pagetitle %}

{% load scipost_extras %}
{% load bootstrap %}

{% block breadcrumb_items %}
  {{block.super}}
  <a href="{% url 'invitations:list' %}" class="breadcrumb-item">Registration Invitations</a>
  <span class="breadcrumb-item">New</span>
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-12">
      <h1 class="highlight">New Registration Invitation</h1>
      <p>
        If you want to invite a new Contributor to SciPost, first try to use the following search form to see if this person already is available in the SciPost database.
      </p>

      {% if suggestion_search_form %}
        <h3 class="mb-1">Search for existing Contributor</h3>
        <form method="get">
          {{ suggestion_search_form|bootstrap }}
          <input type="submit" class="btn btn-primary" value="Search">
          {% if suggestion_search_form.is_bound %}
            <a href="{% url 'invitations:new' %}" class="ms-2 btn btn-link">Cancel search</a>
          {% endif %}
        </form>

        <hr class="divider">
        {% if suggestion_search_form.is_bound %}
          {% if suggested_invitations %}
            <h3>Registration Invitations found</h3>
            <p>
              If the person you are trying to invite is within this list of Registration Invitations, please use it by extending that particular invitation.
            </p>
            <ul class="mb-2">
              {% for inv in suggested_invitations %}
                <li><a href="{% url 'invitations:add_citation' inv.id %}">Use Registration Invitation for {{ inv.first_name }} {{ inv.last_name }}</a></li>
              {% endfor %}
            </ul>
          {% endif %}
          {% if declined_invitations %}
            <h3>Declined Registration Invitations</h3>
            <p>
              If the person you are trying to invite is within this list of Registration Invitations, do not invite them again. They have already declined an earlier invitation.
            </p>
            <ul class="mb-2">
              {% for inv in declined_invitations %}
                <li>{{ inv.first_name }} {{ inv.last_name }}: {{ inv.email }}</a></li>
              {% endfor %}
            </ul>
          {% endif %}

          <h3>Citation Notification</h3>
          <p>
            If the person you are trying to invite is already a registered Contributor, it'll be listed in the following form. If not, you can <a href="{% url 'invitations:new' %}?prefill-last_name={{ suggestion_search_form.last_name.value|urlencode }}">write a new Registration Invitation</a>.
          </p>
        {% else %}
          <h3 class="mb-1">...or write a new Registration Invitation</h3>
        {% endif %}

      {% endif %}

      {% if suggestion_search_form.is_bound %}
        <form method="post">
          {% csrf_token %}
          {{ citation_form|bootstrap }}
          <button type="submit" class="btn btn-primary" name="save" value="save">Save</button>
          <button type="submit" class="ms-2 btn btn-primary" name="save" value="save_and_create">Save and create new</button>
          {% if perms.scipost.can_manage_registration_invitations %}
            <button type="submit" class="ms-2 btn btn-outline-secondary" name="save" value="save_and_send">Save and send mail</button>
          {% endif %}
        </form>

        <br>
        <a href="{% url 'invitations:new' %}">Cancel search here</a> to write a new Registration Invitation.
      {% else %}
        <form method="post">
          {% csrf_token %}
          {{ invitation_form|bootstrap }}
          <button type="submit" class="btn btn-primary" name="save" value="save">Save</button>
          <button type="submit" class="ms-2 btn btn-primary" name="save" value="save_and_create">Save and create new</button>
        </form>
      {% endif %}
    </div>
  </div>

{% endblock %}

{% block footer_script %}
  {{ block.super }}
  {{ citation_form.media }}
  {{ invitation_form.media }}
{% endblock footer_script %}

scipost_django/invitations/templates/invitations/registrationinvitation_list.html
{% extends 'scipost/_personal_page_base.html' %}

{% load bootstrap %}

{% block pagetitle %}: Registration Invitations{% endblock pagetitle %}

{% block breadcrumb_items %}
  {{block.super}}
  <span class="breadcrumb-item">Registration Invitations</span>
{% endblock %}

{% block content %}

  <h1 class="highlight">Registration Invitations</h1>

  <div class="row">
    <div class="col-md-6">
      <h3>Actions</h3>
      <ul class="mb-0">
        {% if perms.scipost.can_create_registration_invitations %}
          <li><a href="{% url 'invitations:new' %}">Create a new invitation</a></li>
        {% endif %}
        {% if perms.scipost.can_manage_registration_invitations %}
          <li><a href="{% url 'invitations:cleanup' %}">Perform a cleanup</a></li>
          <li><a href="{% url 'invitations:citation_notification_list' %}">List unprocessed Citation Notifications ({{ count_unprocessed }})<a/></li>
            <li><a href="{% url 'invitations:list_contributors' %}">List draft Contributor Invitations (to be sent)</a></li>
        {% endif %}
        {% if perms.scipost.can_invite_fellows %}
          <li><a href="{% url 'invitations:list_fellows' %}">List Fellow Invitations</a></li>
        {% endif %}

        <li><a href="{% url 'invitations:list_sent' %}">Show all Invitations pending response</a></li>
      </ul>
    </div>
    <div class="col-md-6 text-md-right">
      <h3>Quick stats</h3>
      Number in draft: {{ count_in_draft }}<br>
      Number pending response: {{ count_pending }}

      {% if perms.scipost.can_create_registration_invitations %}
        <br><br>
        <a href="{% url 'invitations:new' %}" class="btn btn-primary">Create a new invitation</a>
      {% endif %}
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <h2 class="highlight">Registration Invitations</h2>
    </div>
    <div class="col-md-6">
      <form method="get">
        {{ search_form|bootstrap }}
        <input class="btn btn-primary" type="submit" value="Filter">
        <a href="{% url 'invitations:list' %}" class="btn btn-link">Reset filter</a>
      </form>
    </div>
    {% if is_paginated %}
      <div class="col-12">
        {% include '_pagination.html' with page_obj=page_obj %}
      </div>
    {% endif %}
    <div class="col-12">
      <br>
      {% include 'invitations/_registrationinvitation_table.html' with invitations=object_list %}
      {% if search_form.is_bound %}
        <a href="{% url 'invitations:list' %}" class="btn btn-link">Reset filter</a>
      {% endif %}
    </div>
    {% if is_paginated %}
      <div class="col-12">
        {% include '_pagination.html' with page_obj=page_obj %}
      </div>
    {% endif %}
  </div>

{% endblock %}

scipost_django/invitations/templates/invitations/registrationinvitation_list_fellows.html
{% extends 'scipost/_personal_page_base.html' %}

{% load bootstrap %}

{% block pagetitle %}: Registration Invitations{% endblock pagetitle %}

{% block breadcrumb_items %}
  {{block.super}}
  <a href="{% url 'invitations:list' %}" class="breadcrumb-item">Registration Invitations</a>
  <span class="breadcrumb-item">Fellows</span>
{% endblock %}

{% block content %}

  <h1 class="highlight">Registration Invitations Fellows</h1>


  <div class="row">
    {% if is_paginated %}
      <div class="col-12">
        {% include '_pagination.html' with page_obj=page_obj %}
      </div>
    {% endif %}
    <div class="col-12">
      <br>

      {% include 'invitations/_registrationinvitation_table.html' with invitations=object_list %}
      {% if search_form.is_bound %}
        <a href="{% url 'invitations:list_sent' %}" class="btn btn-link">Reset filter</a>
      {% endif %}
    </div>
    {% if is_paginated %}
      <div class="col-12">
        {% include '_pagination.html' with page_obj=page_obj %}
      </div>
    {% endif %}
  </div>

{% endblock %}

scipost_django/invitations/templates/invitations/registrationinvitation_list_sent.html
{% extends 'scipost/_personal_page_base.html' %}

{% load bootstrap %}

{% block pagetitle %}: Registration Invitations{% endblock pagetitle %}

{% block breadcrumb_items %}
  {{block.super}}
  <a href="{% url 'invitations:list' %}" class="breadcrumb-item">Registration Invitations</a>
  <span class="breadcrumb-item">Sent</span>
{% endblock %}

{% block content %}

  <h1 class="highlight">Sent Registration Invitations</h1>


  <div class="row">
    <div class="col-12">
      <form method="get">
        {{ search_form|bootstrap }}
        <input class="btn btn-primary" type="submit" value="Filter">
        <a href="{% url 'invitations:list_sent' %}" class="btn btn-link">Reset filter</a>
      </form>
    </div>
    {% if is_paginated %}
      <div class="col-12">
        {% include '_pagination.html' with page_obj=page_obj %}
      </div>
    {% endif %}
    <div class="col-12">
      <br>

      {% include 'invitations/_registrationinvitation_table.html' with invitations=object_list %}
      {% if search_form.is_bound %}
        <a href="{% url 'invitations:list_sent' %}" class="btn btn-link">Reset filter</a>
      {% endif %}
    </div>
    {% if is_paginated %}
      <div class="col-12">
        {% include '_pagination.html' with page_obj=page_obj %}
      </div>
    {% endif %}
  </div>

{% endblock %}