scipost_django/api/urls.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.urls import include, path

from rest_framework import routers


# colleges
from colleges.api.viewsets import FellowshipPublicAPIViewSet

# journals
from journals.api.viewsets import (
    PublicationPublicAPIViewSet,
    PublicationPublicSearchAPIViewSet,
    PubFracPublicAPIViewSet,
)

# submissions
from submissions.api.viewsets import (
    SubmissionPublicAPIViewSet,
    SubmissionPublicSearchAPIViewSet,
)

# organizations
from organizations.api.viewsets import (
    OrganizationPublicAPIViewSet,
    OrganizationNAPViewSet,
)

# finances
from finances.api.viewsets import SubsidyFinAdminAPIViewSet, SubsidyPublicAPIViewSet


# Next two: old style, to be deprecated:
from conflicts.viewsets import ConflictOfInterestViewSet
from news.viewsets import NewsItemViewSet

# Utilities
from api.views.omniauth import OmniAuthUserInfoView
import api.views.search as search_views


app_name = "api"


router = routers.SimpleRouter()

# search (Vue-based) routes
router.register(
    "search/publications",
    PublicationPublicSearchAPIViewSet,
    basename="search_publications",
)
router.register(
    "search/submissions",
    SubmissionPublicSearchAPIViewSet,
    basename="search_submissions",
)

#############################
# publicly-accessible routes
#############################

# colleges
router.register("colleges/fellowships", FellowshipPublicAPIViewSet)


# journals
router.register("publications", PublicationPublicAPIViewSet)
router.register("pubfracs", PubFracPublicAPIViewSet)

# submissions
router.register("submissions", SubmissionPublicAPIViewSet)

# organizations
router.register("organizations", OrganizationPublicAPIViewSet)
router.register("nap", OrganizationNAPViewSet, basename="organization_nap")

# finances
router.register(
    "finadmin/subsidies", SubsidyFinAdminAPIViewSet, basename="subsidies_finadmin"
)
router.register("subsidies", SubsidyPublicAPIViewSet)

# Next two: old style, to be deprecated:
router.register(r"news", NewsItemViewSet)
router.register(r"conflicts", ConflictOfInterestViewSet)


urlpatterns = router.urls


urlpatterns += [
    path(  # /api/omniauth/userinfo/, for SciPost as GitLab/OmniAuth authorization server
        "omniauth/userinfo/", OmniAuthUserInfoView.as_view(), name="omniauth_userinfo"
    ),
    path(  # /api/available_search_tabs/
        "available_search_tabs/",
        search_views.available_search_tabs,
        name="available_search_tabs",
    ),
]

scipost_django/ontology/urls.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.urls import path

from . import views

app_name = "ontology"

urlpatterns = [
    path(
        "acad_field-autocomplete/",
        views.AcademicFieldAutocompleteView.as_view(),
        name="acad_field-autocomplete",
    ),
    path(
        "specialty-autocomplete/",
        views.SpecialtyAutocompleteView.as_view(),
        name="specialty-autocomplete",
    ),
    path(
        "specialty/autocomplete/dynsel",
        views.HXDynselSpecialtyAutocomplete.as_view(),
        name="specialty_dynsel",
    ),
    path(
        "tag-autocomplete/",
        views.TagAutocompleteView.as_view(),
        name="tag-autocomplete",
    ),
    path(
        "topic-autocomplete/",
        views.TopicAutocompleteView.as_view(),
        name="topic-autocomplete",
    ),
    path(
        "topic-linked-autocomplete/",
        views.TopicLinkedAutocompleteView.as_view(),
        name="topic-linked-autocomplete",
    ),
    path(
        "_hx_topic_dynsel_list",
        views._hx_topic_dynsel_list,
        name="_hx_topic_dynsel_list",
    ),
    path(
        "set_session_acad_field",
        views.set_session_acad_field,
        name="set_session_acad_field",
    ),
    path(
        "_hx_session_specialty_form",
        views._hx_session_specialty_form,
        name="_hx_session_specialty_form",
    ),
    path(
        "set_session_specialty",
        views.set_session_specialty,
        name="set_session_specialty",
    ),
    path("", views.ontology, name="ontology"),
    path("topic/add/", views.TopicCreateView.as_view(), name="topic_create"),
    path("topic/<slug:slug>/add_tags/", views.topic_add_tags, name="topic_add_tags"),
    path(
        "topic/<slug:slug>/remove_tag/<int:tag_id>/",
        views.topic_remove_tag,
        name="topic_remove_tag",
    ),
    path(
        "topic/<slug:slug>/update/",
        views.TopicUpdateView.as_view(),
        name="topic_update",
    ),
    path("topic/<slug:slug>/", views.TopicDetailView.as_view(), name="topic_details"),
    path("topics/", views.TopicListView.as_view(), name="topics"),
    path(
        "topics/_hx_form",
        views._hx_topic_search_form,
        name="_hx_topic_search_form",
    ),
    path(
        "topics/_hx_table",
        views._hx_topic_table,
        name="_hx_topic_table",
    ),
    path(
        "add_relation_asym/<slug:slug>/",
        views.add_relation_asym,
        name="add_relation_asym",
    ),
    path(
        "delete_relation_asym/<int:relation_id>/<slug:slug>/",
        views.delete_relation_asym,
        name="delete_relation_asym",
    ),
]

scipost_django/ontology/models/academic_field.py
_copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.db import models

from journals.models import Journal


class AcademicField(models.Model):
    """
    A principal division of a branch of knowledge.
    """

    branch = models.ForeignKey(
        "ontology.Branch", on_delete=models.CASCADE, related_name="academic_fields"
    )

    name = models.CharField(max_length=128)

    slug = models.SlugField(unique=True, allow_unicode=True)

    order = models.PositiveSmallIntegerField()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["branch", "order"], name="unique_branch_order"
            ),
        ]
        ordering = [
            "branch",
            "order",
        ]

    def __str__(self):
        return self.name

    @property
    def journals(self):
        return Journal.objects.filter(college__acad_field=self.id)

scipost_django/ontology/models/branch.py
_copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.db import models

from journals.models import Journal
from submissions.models import Submission


class Branch(models.Model):
    """
    A principal division in the tree of knowledge.
    """

    name = models.CharField(max_length=128)

    slug = models.SlugField(unique=True, allow_unicode=True)

    order = models.PositiveSmallIntegerField(unique=True)

    class Meta:
        ordering = [
            "order",
        ]
        verbose_name_plural = "branches"

    def __str__(self):
        return self.name

    @property
    def journals(self):
        return Journal.objects.filter(college__acad_field__branch=self.id)

    @property
    def submissions(self):
        return Submission.objects.public_latest().filter(acad_field__branch=self.id)

scipost_django/ontology/models/relations.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.db import models

from ..constants import TOPIC_RELATIONS_ASYM, TOPIC_RELATIONS_SYM


class RelationAsym(models.Model):
    """
    An asymmetric Relation between two Topics.
    """

    A = models.ForeignKey(
        "ontology.Topic", on_delete=models.CASCADE, related_name="relation_LHS"
    )
    relation = models.CharField(max_length=32, choices=TOPIC_RELATIONS_ASYM)
    B = models.ForeignKey(
        "ontology.Topic", on_delete=models.CASCADE, related_name="relation_RHS"
    )

    def __str__(self):
        return "%s %s %s" % (self.A, self.get_relation_display(), self.B)


class RelationSym(models.Model):
    """
    A symmetric relation between multiple Topics.
    """

    topics = models.ManyToManyField("ontology.Topic")
    relation = models.CharField(max_length=32, choices=TOPIC_RELATIONS_SYM)

    def __str__(self):
        text = ", ".join(self.topics.values_list("name", flat=True))
        text += self.get_relation_display()
        return text

scipost_django/ontology/models/specialty.py
_copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.db import models

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ontology.models import AcademicField, Topic


class Specialty(models.Model):
    """
    A principal division of an AcademicField.
    """

    acad_field = models.ForeignKey["AcademicField"](
        "ontology.AcademicField", on_delete=models.CASCADE, related_name="specialties"
    )

    topics = models.ManyToManyField["Specialty", "Topic"](
        "ontology.Topic",
        related_name="specialties",
        blank=True,
    )

    name = models.CharField(max_length=128)

    slug = models.SlugField(unique=True, allow_unicode=True)

    order = models.PositiveSmallIntegerField()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["acad_field", "order"], name="unique_acad_field_order"
            ),
        ]
        ordering = [
            "acad_field",
            "order",
        ]
        verbose_name_plural = "specialties"

    def __str__(self):
        return self.name

    @property
    def code(self):
        """
        Capitalized letter code representing the specialty.
        """
        return self.slug.partition("-")[2].upper()

scipost_django/ontology/models/tag.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.db import models


class Tag(models.Model):
    """
    Tags can be attached to a Topic to specify which category it fits.
    Examples: Concept, Device, Model, Theory, ...
    """

    name = models.CharField(max_length=32, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

scipost_django/ontology/models/topic.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.db import models
from django.urls import reverse


class Topic(models.Model):
    """
    A Topic represents one of the nodes in the ontology.
    """

    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(unique=True, allow_unicode=True)
    tags = models.ManyToManyField("ontology.Tag", blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_abolute_url(self):
        return reverse("ontology:topic_details", kwargs={"slug": self.slug})

scipost_django/edadmin/views/base.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


import operator

from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, render

from guardian.shortcuts import get_objects_for_user

from colleges.permissions import is_edadmin
from submissions.models import Submission


@login_required
@user_passes_test(is_edadmin)
def edadmin(request):
    """
    Editorial administration page.
    """
    context = {"stages": Submission.STAGE_SLUGS}
    return render(request, "edadmin/edadmin.html", context)


@login_required
@user_passes_test(is_edadmin)
def _hx_submissions_in_stage(request, stage):
    """
    List Submissions in a given stage.
    """
    if stage not in Submission.STAGE_SLUGS:
        raise Http404(f"This Submission stage does not exist: {stage}")
    submissions = get_objects_for_user(request.user, "submissions.take_edadmin_actions")
    submissions = operator.attrgetter(f"in_stage_{stage}")(submissions)()
    paginator = Paginator(submissions, 16)
    page_nr = request.GET.get("page")
    page_obj = paginator.get_page(page_nr)
    count = paginator.count
    start_index = page_obj.start_index
    context = {
        "stage": stage,
        "count": count,
        "page_obj": page_obj,
        "start_index": start_index,
    }
    return render(request, "edadmin/_hx_submissions.html", context)


@login_required
@user_passes_test(is_edadmin)
def _hx_submission_details_contents(request, identifier_w_vn_nr):
    submission = get_object_or_404(
        Submission, preprint__identifier_w_vn_nr=identifier_w_vn_nr
    )
    context = {
        "submission": submission,
    }
    return render(request, "edadmin/_hx_submission_details_contents.html", context)


@login_required
@user_passes_test(is_edadmin)
def _hx_submission_tab_contents_edadmin(request, identifier_w_vn_nr):
    submission = get_object_or_404(
        Submission, preprint__identifier_w_vn_nr=identifier_w_vn_nr
    )
    context = {
        "submission": submission,
    }
    return render(request, "edadmin/_hx_submission_tab_contents_edadmin.html", context)

scipost_django/ontology/templates/ontology/_hx_topic_dynsel_list.html
{% load ontology_extras %}

<ul class="list list-unstyled dynsel-list">
  {% for topic in topics|slice:":11" %}
    {% if forloop.counter == 11 %}
      <li>&emsp;...</li>
    {% else  %}
      <li class="m-1">
	<a
	    hx-get="{% topic_dynsel_action_url topic %}"
	    hx-target="#{{ action_target_element_id }}"
	    hx-swap="{{ action_target_swap }}"
	    hx-indicator="#{{ action_target_element_id }}-indicator"
	>
	  {{ topic }}
	</a>
      </li>
    {% endif %}
  {% endfor %}
</ul>

scipost_django/ontology/templates/ontology/_hx_topic_search_form.html
{% load crispy_forms_tags %}

<form hx-post="{% url 'ontology:_hx_topic_table' %}"
      hx-trigger="load, keyup delay:500ms, change delay:500ms, click from:#refresh-button"
      hx-sync="#topic-search-form:replace"
      hx-target="#topic-search-results"
      hx-indicator="#topic-search-indicator">

  <div id="topic-search-form">{% crispy form %}</div>
</form>

scipost_django/ontology/templates/ontology/_hx_topic_table.html
{% for topic in page_obj %}
  {% include 'ontology/_hx_topic_table_row.html' %}
{% empty %}
  <tr id="topic-search-results-load-next" hx-swap-oob="true">
    <td colspan="12" class="text-center p-0">
      <div class="p-2 d-flex justify-content-center">
        <strong>No Profiles could be found</strong>
      </div>
    </td>
  </tr>
{% endfor %}

{% if page_obj.has_next %}
  <tr id="topic-search-results-load-next"
      class="htmx-indicator"
      hx-swap-oob="true"
      hx-post="{% url 'ontology:_hx_topic_table' %}?page={{ page_obj.next_page_number }}"
      hx-target="#topic-search-results"
      hx-include="#topic-search-form"
      hx-trigger="revealed"
      hx-swap="beforeend"
      hx-indicator="#topic-search-results-load-next">

    <td colspan="12" class="text-center p-0">
      <div class="p-2 bg-primary bg-opacity-25 d-flex justify-content-center">
        <strong>Loading page {{ page_obj.next_page_number }} out of {{ page_obj.paginator.num_pages }}</strong>
        <div class="spinner-grow spinner-grow-sm ms-2"
             role="status"
             aria-hidden="true"></div>
      </div>
    </td>
  </tr>
{% else %}
  <tr id="topic-search-results-load-next" hx-swap-oob="true">

    <td colspan="12" class="text-center p-0">
      <div class="p-2 d-flex justify-content-center">
        <strong>All Topics loaded</strong>
      </div>
    </td>
  </tr>
{% endif %}

scipost_django/ontology/templates/ontology/_hx_topic_table_row.html
<tr>
  <td style="min-width: 400px;">
    <a href="{% url 'ontology:topic_details' topic.slug %}">{{ topic.name }}</a>
  </td>
  <td>{{ topic.nr_submissions }} / {{ topic.nr_publications }}</td>
  <td>
    <div class="d-flex flex-wrap gap-2">

      {% for specialty in topic.specialties.all %}
        <span class="badge text-dark bg-light">{{ specialty.name }}</span>
      {% endfor %}

    </div>
  </td>
  <td>
    <div class="d-flex flex-wrap gap-2">

      {% for tag in topic.tags.all %}
        <span class="badge text-dark bg-light">{{ tag.name }}</span>
      {% endfor %}


    </div>
  </td>

</tr>

scipost_django/ontology/templates/ontology/_topic_card.html
{% load bootstrap %}

{% load profiles_extras %}

<div class="card">
  <div class="card-header">
    <ul class="list-inline">
      <li class="list-inline-item"><h3>{{ topic }}</h3></li>
      {% if perms.scipost.can_manage_ontology %}
	<li class="list-inline-item small">
	  <a href="{% url 'ontology:topic_update' slug=topic.slug %}">Update</a>
	</li>
      {% endif %}
    </ul>
    {% if topic.tags.all or perms.scipost.can_manage_ontology %}
      <ul class="list list-inline mb-0">
	<li class="list-inline-item"><strong>Tags</strong>:</li>
	{% for tag in topic.tags.all %}
	  <li class="list-inline-item">{{ tag }}{% if perms.scipost.can_manage_ontology %} <a href="{% url 'ontology:topic_remove_tag' slug=topic.slug tag_id=tag.id %}"><span class="text-danger">{% include 'bi/x-circle-fill.html' %}</span></a>{% endif %}</li>
	{% endfor %}
	{% if perms.scipost.can_manage_ontology %}
	  <form class="p-2" action="{% url 'ontology:topic_add_tags' slug=topic.slug %}" method="post">
	    {% csrf_token %}
	    <ul class="list list-inline">
	      <li class="list-inline-item">{{ select_tags_form }}</li>
	      <li class="list-inline-item"><input type="submit" class="btn btn-outline-secondary" value="Add Tag(s)"></li>
	    </ul>
	  </form>
	{% endif %}
      </ul>
    {% endif %}
  </div>

  <div class="card-body">
    {% if relations_asym or topic.relationsym_set.all or perms.scipost.can_manage_ontology %}
      <h4>Relations to other Topics</h4>
      <div class="row mb-0">
	<div class="col-6">
	  <h5>asymmetric:</h5>
	  <ul>
	    {% for rel in relations_asym %}
	      <li>{% if rel.A != topic %}<a href="{% url 'ontology:topic_details' slug=rel.A.slug %}">{{ rel.A}}</a>{% else %}{{ rel.A }}{% endif %} <em>{{ rel.get_relation_display }}</em> {% if rel.B != topic %}<a href="{% url 'ontology:topic_details' slug=rel.B.slug %}">{{ rel.B }}</a>{% else %}{{ rel.B }}{% endif %} {% if perms.scipost.can_manage_ontology %}<a href="{% url 'ontology:delete_relation_asym' relation_id=rel.id slug=topic.slug %}"><span class="text-danger">{% include 'bi/x-circle-fill.html' %}</span></a>{% endif %}</li>
	    {% empty %}
	      <li>No relations have been defined</li>
	    {% endfor %}
	  </ul>
	  {% if perms.scipost.can_manage_ontology %}
	    <h5>Add an asymmetric relation:</h5>
	    <form action = "{% url 'ontology:add_relation_asym' slug=topic.slug %}" method="post">
	      {% csrf_token %}
	      {{ add_relation_asym_form }}
	      <input type="submit" class="btn btn-outline-secondary" value="Add"/>
	    </form>
	  {% endif %}
	</div>
	<div class="col-6">
	  <h5>symmetric:</h5>
	  <ul>
	    {% for rel in topic.relationsym_set.all %}
	      <li>{% for reltopic in rel.topics.all %}{% if reltopic != topic %}<a href="{% url 'ontology:topic_details' slug=reltopic.slug %}">{{ reltopic }}</a>{% else %}{{ reltopic }}{% endif %}, {% endfor %} <em>{{ rel.get_relation_display }}</em></li>
	    {% empty %}
	      <li>No symmetric relations have been defined</li>
	    {% endfor %}
	  </ul>
	</div>
      </div>
      <hr/>
    {% endif %}
    <div class="row">
      <div class="col-md-6 col-lg-4 mb-2">
	<div class="card">
	  <div class="card-header">
	    Publications
	  </div>
	  <div class="card-body">
	    <ul>
	      {% for pub in topic.publications.all %}
		<li>
		  <a href="{{ pub.get_absolute_url }}">{{ pub.title }}</a>
		  <br>by {{ pub.author_list }},
		  <br>{{ pub.citation }}
		</li>
	      {% empty %}
		<li>No Publication found</li>
	      {% endfor %}
	    </ul>
	  </div>
	</div>
      </div>
      <div class="col-md-6 col-lg-4 mb-2">
	<div class="card">
	  <div class="card-header">
	    Submissions (unpublished only)
	  </div>
	  <div class="card-body">
	    <ul>
	      {% for sub in topic.submission_set.public_latest.unpublished %}
    		<li>
    		  <a href="{{ sub.get_absolute_url }}">{{ sub.title }}</a>
    		  <br>by {{ sub.author_list }}
    		  <br>(submitted {{ sub.submission_date|date:"Y-m-d" }} to {{ sub.submitted_to }})
    		</li>
	      {% empty %}
		<li>No Submission found</li>
	      {% endfor %}
	    </ul>
	  </div>
	</div>
      </div>
      <div class="col-md-6 col-lg-4 mb-2">
	<div class="card">
	  <div class="card-header">
	    Top experts
	  </div>
	  <div class="card-body">
	    <ul>
	      {% get_profiles topic.slug as profiles %}
	      {% for profile in profiles %}
		{% if profile.contributor %}
		  <li><a href="{{ profile.contributor.get_absolute_url }}">{{ profile }}</a></li>
		{% else %}
		  <li>{{ profile }}</li>
		{% endif %}
	      {% empty %}
		<li>No Profile found</li>
	      {% endfor %}
	    </ul>
	  </div>
	</div>
      </div>
    </div>
  </div>
</div>

{% block footer_script %}
  {{ select_tags_form.media }}
  {{ add_relation_asym_form.media }}
{% endblock %}

scipost_django/ontology/templates/ontology/base.html
{% extends 'scipost/base.html' %}

{% block breadcrumb %}
  <div class="breadcrumb-container">
    <div class="container">
      <nav class="breadcrumb hidden-sm-down">
        {% block breadcrumb_items %}
          <a href="{% url 'ontology:ontology' %}" class="breadcrumb-item">Ontology</a>
        {% endblock %}
      </nav>
    </div>
  </div>
{% endblock %}

{% block meta_description %}{{ block.super }} Ontology{% endblock meta_description %}

scipost_django/ontology/templates/ontology/ontology.html
{% extends 'ontology/base.html' %}

{% block pagetitle %}: Ontology{% endblock pagetitle %}

{% block breadcrumb_items %}
  {{ block.super }}
  <span class="breadcrumb-item">Welcome</span>
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-12">
      <h3 class="highlight">Ontology</h3>
      <ul class="list-inline">
	{% if perms.scipost.can_manage_ontology %}
	  <li class="list-inline-item ms-2 me-2"><a href="{% url 'ontology:topic_create' %}">Add a Topic</a></li>
	{% endif %}
	<li class="list-inline-item ms-2 me-2"><a href="{% url 'ontology:topics' %}">View list of Topics</a></li>
	<li class="list-inline-item ms-2 me-2">{{ select_linked_topic_form }}</li>
      </ul>
      <p>
	Welcome to SciPost's Ontology, which is a curated set of interlinked Topics
	pertaining to all of the sciences.
      </p>
      <p>
	Topics and their relations are defined by Editorial-level personnel.
	The ontology is used at many levels within SciPost, including but not limited to:
	<ul>
    	  <li>identifying the best potential Editors-in-charge for incoming submissions</li>
    	  <li>identifying thematic areas for which the editorial workforce should be increased</li>
    	  <li>providing Editors-in-charge with referee suggestions</li>
    	  <li>giving readers a way to identify interesting published content</li>
    	  <li>assisting our internal metadata- and content-driven engines.</li>
	</ul>
      </p>
      <p>
	The Ontology is currently under development.
      </p>
    </div>
  </div>

{% endblock content %}

{% block footer_script %}
  {{ block.super }}
  {{ select_linked_topic_form.media }}
{% endblock footer_script %}

scipost_django/ontology/templates/ontology/session_acad_field_form.html
{% load crispy_forms_tags %}
<form id="session_acad_field_form"
      hx-get="{% url 'ontology:set_session_acad_field' %}"
      hx-trigger="change"
      hx-swap="outerHTML"
>
  {% crispy session_acad_field_form %}
</form>

scipost_django/ontology/templates/ontology/session_specialty_form.html
{% load crispy_forms_tags %}
<form id="session_specialty_form"
      hx-get="{% url 'ontology:set_session_specialty' %}"
      hx-trigger="change"
      hx-swap="outerHTML"
>
  {% crispy session_specialty_form %}
</form>

scipost_django/ontology/templates/ontology/topic_detail.html
{% extends 'ontology/base.html' %}

{% load bootstrap %}

{% block breadcrumb_items %}
  {{ block.super }}
  <span class="breadcrumb-item"><a href="{% url 'ontology:topics' %}">Topics</a></span>
  <span class="breadcrumb-item">{{ topic }}</span>
{% endblock %}

{% block meta_description %}{{ block.super }} Topic detail {{ topic }}{% endblock meta_description %}
{% block pagetitle %}: Topic details{% endblock pagetitle %}

{% block content %}
  <div class="row">
    <div class="col-12">
      {% include 'ontology/_topic_card.html' with topic=topic select_tag_form=select_tag_form %}
    </div>
  </div>
{% endblock content %}

{% block footer_script %}
  {{ block.super }}
  {{ select_tag_form.media }}
{% endblock footer_script %}

scipost_django/ontology/templates/ontology/topic_list.html
{% extends 'ontology/base.html' %}

{% block meta_description %}
  {{ block.super }} Topics list
{% endblock meta_description %}

{% block pagetitle %}
  : Topics
{% endblock pagetitle %}

{% block breadcrumb_items %}
  {{ block.super }}
  <span class="breadcrumb-item">Topics</span>
{% endblock %}

{% block content %}
  <h1>Topics</h1>

  <details open id="topic-filter-details" class="card my-4">
    <summary class="card-header d-flex flex-row align-items-center justify-content-between list-triangle">
      <div class="fs-3">Search / Filter</div>
      <div class="d-none d-md-flex align-items-center">

        <div id="topic-search-indicator" class="htmx-indicator">
          <button class="btn btn-warning text-white d-none d-md-block me-2"
                  type="button"
                  disabled>
            <strong>Loading...</strong>

            <div class="spinner-grow spinner-grow-sm ms-2"
                 role="status"
                 aria-hidden="true"></div>
          </button>
        </div>

        <a class="btn btn-success me-2 text-white"
           href="{% url 'ontology:topic_create' %}">
          {% include "bi/plus-square.html" %}
          &nbsp;Add New
        </a>

        <a id="refresh-button" class="me-2 btn btn-primary">
          {% include "bi/arrow-clockwise.html" %}
        &nbsp;Refresh</a>
      </div>

    </summary>
    <div class="card-body">
      <div id="topic-search-form-container"
           hx-get="{% url 'ontology:_hx_topic_search_form' %}"
           hx-trigger="load once"></div>
    </div>
  </details>

  <section name="search_results" class="p-2">
    <table class="table table-hover table-center table-responsive position-relative">
      <thead class="position-sticky top-0 table-light align-top">
        <tr>
          <th>Name</th>
          <th class="text-nowrap">
            Submissions/
            <br />
            Publications
          </th>
          <th>Specialties</th>
          <th>Tags</th>
        </tr>
      </thead>
      <tbody id="topic-search-results">
      </tbody>
      <tfoot>
        <tr id="topic-search-results-load-next"></tr>
      </tfoot>
    </table>

  </section>


{% endblock content %}


{% block footer_script %}
  {{ block.super }}
  {{ select_linked_topic_form.media }}
{% endblock footer_script %}