scipost_django/api/urls.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.urls import include, path

from rest_framework import routers


# colleges
from colleges.api.viewsets import FellowshipPublicAPIViewSet

# journals
from journals.api.viewsets import (
    PublicationPublicAPIViewSet,
    PublicationPublicSearchAPIViewSet,
    PubFracPublicAPIViewSet,
)

# submissions
from submissions.api.viewsets import (
    SubmissionPublicAPIViewSet,
    SubmissionPublicSearchAPIViewSet,
)

# organizations
from organizations.api.viewsets import (
    OrganizationPublicAPIViewSet,
    OrganizationNAPViewSet,
)

# finances
from finances.api.viewsets import SubsidyFinAdminAPIViewSet, SubsidyPublicAPIViewSet


# Next two: old style, to be deprecated:
from conflicts.viewsets import ConflictOfInterestViewSet
from news.viewsets import NewsItemViewSet

# Utilities
from api.views.omniauth import OmniAuthUserInfoView
import api.views.search as search_views


app_name = "api"


router = routers.SimpleRouter()

# search (Vue-based) routes
router.register(
    "search/publications",
    PublicationPublicSearchAPIViewSet,
    basename="search_publications",
)
router.register(
    "search/submissions",
    SubmissionPublicSearchAPIViewSet,
    basename="search_submissions",
)

#############################
# publicly-accessible routes
#############################

# colleges
router.register("colleges/fellowships", FellowshipPublicAPIViewSet)


# journals
router.register("publications", PublicationPublicAPIViewSet)
router.register("pubfracs", PubFracPublicAPIViewSet)

# submissions
router.register("submissions", SubmissionPublicAPIViewSet)

# organizations
router.register("organizations", OrganizationPublicAPIViewSet)
router.register("nap", OrganizationNAPViewSet, basename="organization_nap")

# finances
router.register(
    "finadmin/subsidies", SubsidyFinAdminAPIViewSet, basename="subsidies_finadmin"
)
router.register("subsidies", SubsidyPublicAPIViewSet)

# Next two: old style, to be deprecated:
router.register(r"news", NewsItemViewSet)
router.register(r"conflicts", ConflictOfInterestViewSet)


urlpatterns = router.urls


urlpatterns += [
    path(  # /api/omniauth/userinfo/, for SciPost as GitLab/OmniAuth authorization server
        "omniauth/userinfo/", OmniAuthUserInfoView.as_view(), name="omniauth_userinfo"
    ),
    path(  # /api/available_search_tabs/
        "available_search_tabs/",
        search_views.available_search_tabs,
        name="available_search_tabs",
    ),
]

scipost_django/production/urls.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.urls import path, re_path, include

from production import views as production_views

app_name = "production"

urlpatterns = [
    # refactoring 2023-05  htmx-driven production page
    path(
        "",
        production_views.production,
        name="production",
    ),
    path(
        "team",
        include(
            [
                path(
                    "",
                    production_views.production_team,
                    name="production_team",
                ),
                path(
                    "list",
                    production_views.production_team_list,
                    name="production_team_list",
                ),
                path(
                    "_hx_delete_officer/<int:officer_id>/",
                    production_views._hx_team_delete_officer,
                    name="_hx_team_delete_officer",
                ),
                path(
                    "_hx_promote_user",
                    production_views._hx_team_promote_user,
                    name="_hx_team_promote_user",
                ),
            ]
        ),
    ),
    path(
        "_hx_productionstream_list",
        production_views._hx_productionstream_list,
        name="_hx_productionstream_list",
    ),
    path(
        "_hx_productionstream_search_form/<str:filter_set>",
        production_views._hx_productionstream_search_form,
        name="_hx_productionstream_search_form",
    ),
    path(
        "_hx_productionstream_actions_bulk_assign_officers",
        production_views._hx_productionstream_actions_bulk_assign_officers,
        name="_hx_productionstream_actions_bulk_assign_officers",
    ),
    path(
        "productionstreams/<int:productionstream_id>/",
        include(
            [
                path(
                    "details_contents",
                    production_views._hx_productionstream_details_contents,
                    name="_hx_productionstream_details_contents",
                ),
                path(
                    "actions_change_properties",
                    production_views._hx_productionstream_actions_change_properties,
                    name="_hx_productionstream_actions_change_properties",
                ),
                path(
                    "actions_work_log",
                    production_views._hx_productionstream_actions_work_log,
                    name="_hx_productionstream_actions_work_log",
                ),
                path(
                    "_hx_productionstream_change_action_buttons/<str:key>",
                    production_views._hx_productionstream_change_action_buttons,
                    name="_hx_productionstream_change_action_buttons",
                ),
                path(
                    "_hx_productionstream_summary_assignees_status",
                    production_views._hx_productionstream_summary_assignees_status,
                    name="_hx_productionstream_summary_assignees_status",
                ),
                path(
                    "events/",
                    include(
                        [
                            path(
                                "form",
                                production_views._hx_event_form,
                                name="_hx_event_form",
                            ),
                            path(
                                "list",
                                production_views._hx_event_list,
                                name="_hx_event_list",
                            ),
                            path(
                                "<int:event_id>/",
                                include(
                                    [
                                        path(
                                            "update",
                                            production_views._hx_event_form,
                                            name="_hx_event_form",
                                        ),
                                        path(
                                            "delete",
                                            production_views._hx_event_delete,
                                            name="_hx_event_delete",
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
    # end refactoring 2023-05
    path("old/", production_views.production_old, name="production_old"),
    path("old/<int:stream_id>", production_views.production_old, name="production_old"),
    path("completed", production_views.completed, name="completed"),
    path("officers/new", production_views.user_to_officer, name="user_to_officer"),
    path(
        "officers/<int:officer_id>/delete",
        production_views.delete_officer,
        name="delete_officer",
    ),
    path(
        "streams/<int:stream_id>/",
        include(
            [
                path("", production_views.stream, name="stream"),
                path("status", production_views.update_status, name="update_status"),
                path(
                    "_hx_status",
                    production_views._hx_update_status,
                    name="_hx_update_status",
                ),
                path(
                    "proofs/",
                    include(
                        [
                            path(
                                "upload",
                                production_views.upload_proofs,
                                name="upload_proofs",
                            ),
                            path(
                                "_hx_upload",
                                production_views._hx_upload_proofs,
                                name="_hx_upload_proofs",
                            ),
                            path(
                                "<int:version>/",
                                include(
                                    [
                                        path(
                                            "", production_views.proofs, name="proofs"
                                        ),
                                        re_path(
                                            "decision/(?P<decision>accept|decline)$",
                                            production_views.decision,
                                            name="decision",
                                        ),
                                        re_path(
                                            "_hx_proofs_decision/(?P<decision>accept|decline)$",
                                            production_views._hx_proofs_decision,
                                            name="_hx_proofs_decision",
                                        ),
                                        path(
                                            "send_to_authors",
                                            production_views.send_proofs,
                                            name="send_proofs",
                                        ),
                                        path(
                                            "_hx_send_to_authors",
                                            production_views._hx_send_proofs,
                                            name="_hx_send_proofs",
                                        ),
                                        path(
                                            "toggle_access",
                                            production_views.toggle_accessibility,
                                            name="toggle_accessibility",
                                        ),
                                        path(
                                            "_hx_toggle_access",
                                            production_views._hx_toggle_accessibility,
                                            name="_hx_toggle_accessibility",
                                        ),
                                    ]
                                ),
                            ),
                            path(
                                "<int:attachment_id>/reply/pdf",
                                production_views.production_event_attachment_pdf,
                                name="production_event_attachment_pdf",
                            ),
                        ]
                    ),
                ),
                path("events/add", production_views.add_event, name="add_event"),
                path("logs/add", production_views.add_work_log, name="add_work_log"),
                path(
                    "officer",
                    include(
                        [
                            path(
                                "add",
                                production_views.add_officer,
                                name="add_officer",
                            ),
                            path(
                                "<int:officer_id>/remove",
                                production_views.remove_officer,
                                name="remove_officer",
                            ),
                            path(
                                "update",
                                production_views._hx_update_officer,
                                name="_hx_update_officer",
                            ),
                        ]
                    ),
                ),
                path(
                    "invitations_officer",
                    include(
                        [
                            path(
                                "add",

scipost_django/edadmin/views/base.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


import operator

from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, render

from guardian.shortcuts import get_objects_for_user

from colleges.permissions import is_edadmin
from submissions.models import Submission


@login_required
@user_passes_test(is_edadmin)
def edadmin(request):
    """
    Editorial administration page.
    """
    context = {"stages": Submission.STAGE_SLUGS}
    return render(request, "edadmin/edadmin.html", context)


@login_required
@user_passes_test(is_edadmin)
def _hx_submissions_in_stage(request, stage):
    """
    List Submissions in a given stage.
    """
    if stage not in Submission.STAGE_SLUGS:
        raise Http404(f"This Submission stage does not exist: {stage}")
    submissions = get_objects_for_user(request.user, "submissions.take_edadmin_actions")
    submissions = operator.attrgetter(f"in_stage_{stage}")(submissions)()
    paginator = Paginator(submissions, 16)
    page_nr = request.GET.get("page")
    page_obj = paginator.get_page(page_nr)
    count = paginator.count
    start_index = page_obj.start_index
    context = {
        "stage": stage,
        "count": count,
        "page_obj": page_obj,
        "start_index": start_index,
    }
    return render(request, "edadmin/_hx_submissions.html", context)


@login_required
@user_passes_test(is_edadmin)
def _hx_submission_details_contents(request, identifier_w_vn_nr):
    submission = get_object_or_404(
        Submission, preprint__identifier_w_vn_nr=identifier_w_vn_nr
    )
    context = {
        "submission": submission,
    }
    return render(request, "edadmin/_hx_submission_details_contents.html", context)


@login_required
@user_passes_test(is_edadmin)
def _hx_submission_tab_contents_edadmin(request, identifier_w_vn_nr):
    submission = get_object_or_404(
        Submission, preprint__identifier_w_vn_nr=identifier_w_vn_nr
    )
    context = {
        "submission": submission,
    }
    return render(request, "edadmin/_hx_submission_tab_contents_edadmin.html", context)

scipost_django/production/templates/production/_hx_productionstream_change_officer.html
{% load bootstrap %}

{% if form.fields.officer.choices|length > 0 %}
    <div id="productionstream-{{ stream.id }}-update-officer">
        <form hx-post="{% url 'production:_hx_update_officer' stream.id %}"
              hx-target="#productionstream-{{ stream.id }}-update-officer"
              hx-swap="outerHTML"
              class="row">
            {% csrf_token %}
            <div class="col">{{ form|bootstrap_purely_inline }}</div>
            <div class="col-12 col-sm-auto col-md-12 col-lg-auto h-100 d-none-empty"
                 hx-post="{% url 'production:_hx_productionstream_change_action_buttons' stream.id 'officer' %}"
                 hx-swap="innerHTML"
                 hx-trigger="change from:select#productionstream_{{ stream.id }}_id_officer"
                 hx-target="this"></div>
        </form>
    </div>
{% endif %}

scipost_django/production/templates/production/_hx_productionstream_details.html
<details id="productionstream-{{ productionstream.id }}-details" class="border border-2 mx-3 p-2 bg-primary bg-opacity-10 
  {% if productionstream.in_stasis %}bg-opacity-25 bg-secondary pe-none{% endif %}
   ">
  <summary class="list-none">
    {% include "production/_productionstream_details_summary_contents.html" with productionstream=productionstream %}
  </summary>


  <div id="productionstream-{{ productionstream.id }}-details-contents"
       class="p-2 mt-2 bg-white"
       hx-get="{% url 'production:_hx_productionstream_details_contents' productionstream_id=productionstream.id %}"
       hx-trigger="toggle once from:#productionstream-{{ productionstream.id }}-details"
       hx-indicator="#indicator-productionstream-{{ productionstream.id }}-details-contents"></div>

</details>

scipost_django/production/templates/production/_hx_productionstream_event_form.html
{% load crispy_forms_tags %}

{% if productionevent_form.instance and productionevent_form.instance.id %}
  <form
      hx-post="{% url 'production:_hx_event_form' productionstream_id=productionstream.id  event_id=productionevent_form.instance.id %}"
      hx-target="#productionstream-{{ productionstream.id }}-details-contents"
  >
    {% crispy productionevent_form %}
  </form>
{% else %}
  <form
      hx-post="{% url 'production:_hx_event_form' productionstream_id=productionstream.id %}"
      hx-target="#productionstream-{{ productionstream.id }}-details-contents"
  >
    {% crispy productionevent_form %}
  </form>
{% endif %}

scipost_django/production/templates/production/_hx_productionstream_list.html
{% for productionstream in page_obj %}
  <div class="ms-3 mt-3">
    <strong>{{ forloop.counter0|add:start_index }} of {{ count }}</strong>
  </div>
  {% include 'production/_hx_productionstream_details.html' with productionstream=productionstream %}
{% empty %}
  <strong>No Production Stream could be found</strong>
{% endfor %}
{% if page_obj.has_next %}
  <div hx-post="{% url 'production:_hx_productionstream_list' %}?page={{ page_obj.next_page_number }}"
       hx-include="#search-productionstreams-form"
       hx-trigger="revealed"
       hx-swap="afterend"
       hx-indicator="#indicator-search-page-{{ page_obj.number }}">
    <div id="indicator-search-page-{{ page_obj.number }}"
         class="htmx-indicator p-2">
      <button class="btn btn-warning" type="button" disabled>
        <strong>Loading page {{ page_obj.next_page_number }} out of {{ page_obj.paginator.num_pages }}</strong>
	
        <div class="spinner-grow spinner-grow-sm ms-2"
             role="status"
             aria-hidden="true"></div>
      </button>
    </div>
  </div>
{% endif %}

scipost_django/production/templates/production/_hx_productionstream_search_form.html
{% load crispy_forms_tags %}

<form hx-post="{% url 'production:_hx_productionstream_list' %}"
      hx-trigger="load, keyup delay:500ms, change delay:500ms, click from:#refresh-button"
      hx-sync="#search-productionstreams-form:replace"
      hx-target="#search-productionstreams-results"
      hx-indicator="#indicator-search-productionstreams">
 
  <div id="search-productionstreams-form">{% crispy form %}</div>
</form>

scipost_django/production/templates/production/_hx_upload_proofs.html
{% load bootstrap %}


<h3>Proofs</h3>
<div class="accordion"
     id="productionstream-{{ stream.id }}-proofs-list-accordion">
  {% for proofs in stream.proofs.all %}
    {% include 'production/_hx_productionstream_actions_proofs_item.html' with i_proof=forloop.counter0|add:1 active_id=total_proofs stream=stream proofs=proofs %}
  {% empty %}
    <div>No Proofs found.</div>
  {% endfor %}
</div>

<div class="row mt-3">
  <div class="col-12">
    <form enctype="multipart/form-data"
          hx-post="{% url 'production:_hx_upload_proofs' stream_id=stream.id %}"
          hx-target="#productionstream-{{ stream.id }}-upload-proofs-body">
      {% csrf_token %}
      {{ form|bootstrap_purely_inline }}
      <input type="submit"
             class="btn btn-primary proof-action-button"
             name="submit"
             value="Upload">
    </form>
  </div>
</div>

scipost_django/production/templates/production/_production_timesheet_card.html
<div class="card-body">
  <table class="table mb-5">
    <thead class="table-light">
      <tr>
	<th>Date</th>
	<th>Stream</th>
	<th>Event</th>
	<th>Duration</th>
      </tr>
    </thead>
    <tbody role="tablist">
      {% for event in events %}
	{% if event.duration %}
	  <tr>
	    <td>{{ event.noted_on }}</td>
	    <td>{{ event.stream }}</td>
	    <td>{{ event.get_event_display }}</td>
	    <td>{{ event.duration }}</td>
	  </tr>
	{% endif %}
      {% empty %}
	<tr>
	  <td colspan="4">No events found.</td>
	</tr>
      {% endfor %}
    </tbody>
  </table>
</div>

scipost_django/production/templates/production/base.html
{% extends 'scipost/base.html' %}

{% block container_class %}{{ block.super }} pb-5{% endblock container_class %}

{% block breadcrumb %}
  <div class="breadcrumb-container">
    <div class="container">
      <nav class="breadcrumb">
        {% block breadcrumb_items %}
          <a href="{% url 'production:production' %}" class="breadcrumb-item">Production page</a>
        {% endblock %}
      </nav>
    </div>
  </div>
{% endblock %}

scipost_django/production/templates/production/completed.html
{% extends 'production/base.html' %}

{% block breadcrumb_items %}
  {{block.super}}
  <span class="breadcrumb-item">Completed production streams</span>
{% endblock %}

{% block pagetitle %}: Completed production streams{% endblock pagetitle %}

{% load bootstrap %}

{% block content %}

  <div class="row">
    <div class="col-12">
      <h1 class="highlight">Completed production streams</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <ul class="list-group list-group-flush">
	{% for stream in streams %}
          <li class="list-group-item">
            {% include 'production/_production_stream_card_completed.html' with stream=stream %}
          </li>
	{% empty %}
          <li class="list-group-item">No completed production streams found.</li>
	{% endfor %}
      </ul>
    </div>
  </div>

{% endblock content %}

scipost_django/production/templates/production/production.html
{% extends 'production/base.html' %}

{% load crispy_forms_tags %}

{% block breadcrumb_items %}<span class="breadcrumb-item">Production streams</span>{% endblock %}

{% block pagetitle %}
  : Production page
{% endblock pagetitle %}


{% block content %}

  <div class="row">
    <div class="col-12 col-sm">
      <h1>Production Streams</h1>
    </div>
    <div class="col-12 col-sm-auto">

      {% if perms.scipost.can_promote_user_to_production_officer %}
        <a class="btn-link fs-4" href="{% url 'production:production_team' %}">Production Team</a>
        &nbsp;|&nbsp;
      {% endif %}

      <a class="btn-link fs-4" href="{% url 'finances:personal_timesheet' %}">Personal Timesheet</a>
    </div>
  </div>

  <details id="productionstreams-filter-details" class="card my-4">
    <summary class="card-header d-flex flex-row align-items-center justify-content-between list-triangle">
      <div class="fs-3">Search / Filter / Bulk Actions</div>
      <div class="d-none d-md-flex align-items-center">
 
        <div id="indicator-search-productionstreams" class="htmx-indicator">
          <button class="btn btn-warning text-white d-none d-md-block me-2"
                  type="button"
                  disabled>
            <strong>Loading...</strong>
 
            <div class="spinner-grow spinner-grow-sm ms-2"
                 role="status"
                 aria-hidden="true"></div>
          </button>
        </div>

        <button class="btn btn-outline-secondary me-2"
                type="button"
                hx-get="{% url 'production:_hx_productionstream_search_form' filter_set="empty" %}"
                hx-target="#productionstream-search-form-container">Clear Filters</button>
 
        <a id="refresh-button" class="m-2 btn btn-primary">
          {% include "bi/arrow-clockwise.html" %}
        &nbsp;Refresh</a>
      </div>

    </summary>
    <div class="card-body">
      <div id="productionstream-search-form-container">
        {% include 'production/_hx_productionstream_search_form.html' with form=search_productionstreams_form %}
      </div>

      {% comment %} Bulk Action buttons {% endcomment %}

      {% if perms.scipost.can_assign_production_officer or perms.scipost.can_assign_production_supervisor %}
        <hr />
        <div hx-get="{% url 'production:_hx_productionstream_actions_bulk_assign_officers' %}"
             hx-trigger="load"></div>
      {% endif %}

    </div>
  </details>

  <div id="search-productionstreams-results" class="mt-2"></div>

{% endblock content %}

scipost_django/production/templates/production/production_old.html
{% extends 'production/base.html' %}

{% block breadcrumb_items %}
  <span class="breadcrumb-item">Production page</span>
{% endblock %}

{% block pagetitle %}: Production page{% endblock pagetitle %}

{% load bootstrap %}
{% load scipost_extras %}
{% load submissions_extras %}

{% block content %}

  <div class="row">
    <div class="col-12">
      <h1 class="highlight">Production</h1>
    </div>
  </div>


  <div class="row">
    <div class="col-12">
      <div class="tab-nav-container">
	<div class="tab-nav-inner">
	  <ul class="nav btn-group personal-page-nav" role="tablist">
            <li class="nav-item btn btn-outline-secondary">
              <a href="#summary" class="nav-link active" data-bs-toggle="tab">Production streams</a>
            </li>
	    <li class="nav-item btn btn-outline-secondary">
	      <a href="#mytimesheet" class="nav-link" data-bs-toggle="tab">My Timesheet</a>
	    </li>
	    {% if perms.scipost.can_promote_user_to_production_officer %}
              <li class="nav-item btn btn-outline-secondary">
		<a href="#officers" class="nav-link" data-bs-toggle="tab">Production Team</a>
              </li>
	    {% endif %}
	  </ul>
	</div>
      </div>
    </div>
  </div>

  <div class="tab-content">
    <div class="tab-pane active" id="summary" role="tabpanel">
      <div class="row">
        <div class="col-12">
          <h2 class="highlight">Production streams</h2>
          <table class="table table-fixed">
            <thead>
              <tr>
                <th style="width: 30%;">Submission</th>
                <th>Target Journal</th>
                <th>Status</th>
                <th class="py-1">
                  Latest activity
                  <br>
                  Submission accepted
                </th>
                <th>Has supervisor</th>
                <th>
                  Production officer
                  <br>
                  Invitations officer
                </th>
              </tr>
            </thead>
            <tbody>
              {% for stream in streams %}
                <tr>
                  <td>
                    <a href="{{ stream.get_absolute_url }}">{{ stream.submission.title }}</a>
                    <br>
                    by {{ stream.submission.author_list }}
                  </td>
                  <td>{{ stream.submission.editorial_decision.for_journal }}</td>
                  <td>
                    <div class="label label-{% if stream.status == 'initiated' %}outline-danger{% else %}secondary{% endif %}">{{ stream.get_status_display }}</div>
		    {% if stream.submission.editorial_decision.status == stream.submission.editorial_decision.AWAITING_PUBOFFER_ACCEPTANCE %}<br><strong class="text-danger">Wait! author<br>acceptance of puboffer<br>required!</strong>{% endif %}
                  </td>
                  <td>
                    {{ stream.latest_activity|timesince }} ago
                    <br>
                    <span class="text-muted">{{ stream.opened|timesince }} ago</span>
                  </td>
                  <td>
                    {% if stream.supervisor %}
                      <span class="text-success">{% include 'bi/check-circle-fill.html' %}</span>
                      {{ stream.supervisor }}
                    {% else %}
                      <span class="text-danger">{% include 'bi/x-circle-fill.html' %}</span>
                    {% endif %}
                  </td>
                  <td>
                    {% if stream.officer %}
                      <span class="text-success">{% include 'bi/check-circle-fill.html' %}</span>
                      {{ stream.officer }}
                    {% else %}
                      <span class="text-danger">{% include 'bi/x-circle-fill.html' %}</span>
                    {% endif %}
                    <br>
                    {% if stream.invitations_officer %}
                      <span class="text-success">{% include 'bi/check-circle-fill.html' %}</span>
                      {{ stream.invitations_officer }}
                    {% else %}
                      <span class="text-danger">{% include 'bi/x-circle-fill.html' %}</span>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="tab-pane" id="mytimesheet" role="tabpanel">
      <div class="row">
	<div class="col-12">
    	  <h2 class="highlight">My Timesheet</h2>
          {% if perms.scipost.can_view_timesheets %}
            <a href="{% url 'finances:timesheets' %}">See team timesheets</a>
          {% endif %}
	</div>
      </div>

      <table class="table mb-5">
	<thead class="table-light">
	  <tr>
	    <th>Date</th>
	    <th>Comment</th>
	    <th>Stream</th>
	    <th>Log type</th>
	    <th>Duration</th>
	  </tr>
	</thead>
	<tbody role="tablist">
	  {% for log in request.user.work_logs.all %}
    	    <tr>
    	      <td>{{ log.work_date }}</td>
    	      <td>{{ log.comments }}</td>
    	      <td>{{ log.content }}</td>
              <td>{{ log.log_type }}</td>
    	      <td>{{ log.duration|duration }}</td>
    	    </tr>
	  {% empty %}
	    <tr>
	      <td colspan="4">No logs found.</td>
	    </tr>
	  {% endfor %}
	</tbody>
      </table>
    </div>

    {% if perms.scipost.can_promote_user_to_production_officer %}
      <div class="tab-pane" id="officers" role="tabpanel">
        <h2 class="highlight">Production Tream</h2>
        <h3>Current Production Team</h3>
        <ul>
          {% for officer in production_officers %}
            <li>{{ officer }}
              <form action="{% url 'production:delete_officer' officer.id %}" class="d-inline px-1" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger mb-1" value="Remove Officer">
              </form>
            </li>
          {% endfor %}
        </ul>

        {% if new_officer_form %}
          <h3>Promote user to Production Officer</h3>
          <form action="{% url 'production:user_to_officer' %}" method="post">
            {% csrf_token %}
            {{ new_officer_form|bootstrap }}
            <input type="submit" class="btn btn-primary" value="Promote to Production Officer">
          </form>
        {% endif %}
      </div>
    {% endif %}

  </div>

{% endblock content %}

scipost_django/production/templates/production/productionevent_form.html
{% extends 'production/base.html' %}

{% block breadcrumb_items %}
  {{block.super}}
  <span class="breadcrumb-item">Edit production event</span>
{% endblock %}

{% load bootstrap %}

{% block content %}

  <div class="row">
    <div class="col-12">
      <h1 class="highlight">Edit production event</h1>
      {% include 'submissions/_submission_card_content.html' with submission=object.stream.submission %}
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <form method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <input type="submit" class="btn btn-outline-secondary" name="submit" value="Submit">
      </form>
    </ul>
    </div>
  </div>

{% endblock content %}