scipost_django/api/urls.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.urls import include, path

from rest_framework import routers


# colleges
from colleges.api.viewsets import FellowshipPublicAPIViewSet

# journals
from journals.api.viewsets import (
    PublicationPublicAPIViewSet,
    PublicationPublicSearchAPIViewSet,
    PubFracPublicAPIViewSet,
)

# submissions
from submissions.api.viewsets import (
    SubmissionPublicAPIViewSet,
    SubmissionPublicSearchAPIViewSet,
)

# organizations
from organizations.api.viewsets import (
    OrganizationPublicAPIViewSet,
    OrganizationNAPViewSet,
)

# finances
from finances.api.viewsets import SubsidyFinAdminAPIViewSet, SubsidyPublicAPIViewSet


# Next two: old style, to be deprecated:
from conflicts.viewsets import ConflictOfInterestViewSet
from news.viewsets import NewsItemViewSet

# Utilities
from api.views.omniauth import OmniAuthUserInfoView
import api.views.search as search_views


app_name = "api"


router = routers.SimpleRouter()

# search (Vue-based) routes
router.register(
    "search/publications",
    PublicationPublicSearchAPIViewSet,
    basename="search_publications",
)
router.register(
    "search/submissions",
    SubmissionPublicSearchAPIViewSet,
    basename="search_submissions",
)

#############################
# publicly-accessible routes
#############################

# colleges
router.register("colleges/fellowships", FellowshipPublicAPIViewSet)


# journals
router.register("publications", PublicationPublicAPIViewSet)
router.register("pubfracs", PubFracPublicAPIViewSet)

# submissions
router.register("submissions", SubmissionPublicAPIViewSet)

# organizations
router.register("organizations", OrganizationPublicAPIViewSet)
router.register("nap", OrganizationNAPViewSet, basename="organization_nap")

# finances
router.register(
    "finadmin/subsidies", SubsidyFinAdminAPIViewSet, basename="subsidies_finadmin"
)
router.register("subsidies", SubsidyPublicAPIViewSet)

# Next two: old style, to be deprecated:
router.register(r"news", NewsItemViewSet)
router.register(r"conflicts", ConflictOfInterestViewSet)


urlpatterns = router.urls


urlpatterns += [
    path(  # /api/omniauth/userinfo/, for SciPost as GitLab/OmniAuth authorization server
        "omniauth/userinfo/", OmniAuthUserInfoView.as_view(), name="omniauth_userinfo"
    ),
    path(  # /api/available_search_tabs/
        "available_search_tabs/",
        search_views.available_search_tabs,
        name="available_search_tabs",
    ),
]

scipost_django/helpdesk/urls.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.urls import path

from . import views

app_name = "helpdesk"

urlpatterns = [
    path("", views.HelpdeskView.as_view(), name="helpdesk"),
    path(
        "_hx_ticket_search_form/<str:filter_set>",
        views._hx_ticket_search_form,
        name="_hx_ticket_search_form",
    ),
    path(
        "_hx_ticket_search_table",
        views._hx_ticket_search_table,
        name="_hx_ticket_search_table",
    ),
    path(
        "queue/<slug:parent_slug>/add/",
        views.QueueCreateView.as_view(),
        name="queue_create",
    ),
    path("queue/add/", views.QueueCreateView.as_view(), name="queue_create"),
    path(
        "queue/<slug:slug>/update/",
        views.QueueUpdateView.as_view(),
        name="queue_update",
    ),
    path(
        "queue/<slug:slug>/delete/",
        views.QueueDeleteView.as_view(),
        name="queue_delete",
    ),
    path("queue/<slug:slug>/", views.QueueDetailView.as_view(), name="queue_detail"),
    path(
        "queue/<slug:queue_slug>/_hx_ticket_search_form/<str:filter_set>",
        views._hx_ticket_search_form,
        name="_hx_ticket_search_form",
    ),
    path(
        "queue/<slug:queue_slug>/_hx_ticket_search_table",
        views._hx_ticket_search_table,
        name="_hx_ticket_search_table",
    ),
    path(
        "ticket/add/<int:concerning_type_id>/<int:concerning_object_id>/",
        views.TicketCreateView.as_view(),
        name="ticket_create",
    ),
    path("ticket/add/", views.TicketCreateView.as_view(), name="ticket_create"),
    path(
        "ticket/<int:pk>/update/",
        views.TicketUpdateView.as_view(),
        name="ticket_update",
    ),
    path(
        "ticket/<int:pk>/delete/",
        views.TicketDeleteView.as_view(),
        name="ticket_delete",
    ),
    path(
        "ticket/<int:pk>/assign/",
        views.TicketAssignView.as_view(),
        name="ticket_assign",
    ),
    path("ticket/<int:pk>/", views.TicketDetailView.as_view(), name="ticket_detail"),
    path(
        "ticket/<int:pk>/followup/",
        views.TicketFollowupView.as_view(),
        name="ticket_followup",
    ),
    path(
        "ticket/<int:pk>/resolved/",
        views.TicketMarkResolved.as_view(),
        name="ticket_mark_resolved",
    ),
    path(
        "ticket/<int:pk>/closed/",
        views.TicketMarkClosed.as_view(),
        name="ticket_mark_closed",
    ),
]

scipost_django/helpdesk/models.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.template import Template
from django.urls import reverse
from django.utils import timezone

from .constants import (
    TICKET_PRIORITIES,
    TICKET_PRIORITY_URGENT,
    TICKET_PRIORITY_HIGH,
    TICKET_PRIORITY_MEDIUM,
    TICKET_STATUSES,
    TICKET_STATUS_UNASSIGNED,
    TICKET_STATUS_ASSIGNED,
    TICKET_STATUS_PICKEDUP,
    TICKET_STATUS_PASSED_ON,
    TICKET_STATUS_AWAITING_RESPONSE_ASSIGNEE,
    TICKET_STATUS_AWAITING_RESPONSE_USER,
    TICKET_STATUS_RESOLVED,
    TICKET_STATUS_CLOSED,
    TICKET_FOLLOWUP_ACTION_TYPES,
)
from .managers import QueueQuerySet, TicketQuerySet


class Queue(models.Model):
    """
    A Queue is a container for a category of Tickets.

    Each Ticket has a ForeignKey relationship to a specific Queue.
    A Queue is managed by a specific Group specific by `managing_group`,
    and can be responsed to by users in a set of groups defined by the
    `response_groups` field.

    A Queue is visible only to users in managing or response groups,
    and is thus admin/internal only.

    Permissions are handled at object level using `django_guardian`.
    """

    name = models.CharField(max_length=64)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(
        help_text=(
            "You can use plain text, Markdown or reStructuredText; see our "
            '<a href="/markup/help/" target="_blank">markup help</a> pages.'
        )
    )
    managing_group = models.ForeignKey(
        "auth.Group", on_delete=models.CASCADE, related_name="managed_queues"
    )
    response_groups = models.ManyToManyField("auth.Group")
    parent_queue = models.ForeignKey(
        "helpdesk.Queue",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="sub_queues",
    )

    objects = QueueQuerySet.as_manager()

    class Meta:
        ordering = [
            "name",
        ]
        permissions = [
            ("can_manage_queue", "Can manage Queue"),
            ("can_handle_queue", "Can handle Queue"),
            ("can_view_queue", "Can view Queue"),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("helpdesk:queue_detail", kwargs={"slug": self.slug})

    @property
    def nr_unassigned(self):
        return self.tickets.unassigned().count()

    @property
    def nr_assigned(self):
        return self.tickets.assigned().count()

    @property
    def nr_resolved(self):
        return self.tickets.resolved().count()

    @property
    def nr_closed(self):
        return self.tickets.closed().count()

    @property
    def nr_awaiting_handling(self):
        return self.tickets.awaiting_handling().count()

    @property
    def nr_in_handling(self):
        return self.tickets.in_handling().count()

    @property
    def nr_handled(self):
        return self.tickets.handled().count()


class Ticket(models.Model):
    """
    User-created ticket, representing a query or request for assistance.

    Each ticket lives in a Queue.
    """

    queue = models.ForeignKey(
        "helpdesk.Queue",
        on_delete=models.CASCADE,
        related_name="tickets",
        help_text=(
            "Don't worry and just choose the one that "
            "seems most appropriate for your issue"
        ),
    )
    title = models.CharField(max_length=64, default="")
    description = models.TextField(
        help_text=(
            "You can use plain text, Markdown or reStructuredText; see our "
            '<a href="/markup/help/" target="_blank">markup help</a> pages.'
        )
    )
    publicly_visible = models.BooleanField(
        default=False,
        help_text=(
            "Do you agree with this Ticket being made publicly visible "
            "(and appearing, anonymized, in our public Knowledge Base)?"
        ),
    )
    defined_on = models.DateTimeField(default=timezone.now)
    defined_by = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    priority = models.CharField(max_length=32, choices=TICKET_PRIORITIES)
    deadline = models.DateField(blank=True, null=True)
    status = models.CharField(max_length=32, choices=TICKET_STATUSES)
    assigned_to = models.ForeignKey(
        "auth.User",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="assigned_tickets",
    )
    concerning_object_type = models.ForeignKey(
        ContentType, on_delete=models.CASCADE, blank=True, null=True
    )
    concerning_object_id = models.PositiveIntegerField(blank=True, null=True)
    concerning_object = GenericForeignKey(
        "concerning_object_type", "concerning_object_id"
    )

    objects = TicketQuerySet.as_manager()

    class Meta:
        ordering = ["queue", "priority"]
        permissions = [
            ("can_view_ticket", "Can view Ticket"),
        ]

    def __str__(self):
        return "%s-%s: %s" % (self.queue.slug, self.pk, self.title)

    def get_absolute_url(self):
        return reverse("helpdesk:ticket_detail", kwargs={"pk": self.id})

    def latest_followup(self):
        return self.followups.order_by("timestamp").last()

    @property
    def latest_activity(self):
        try:
            return self.latest_followup().timestamp
        except AttributeError:
            return self.defined_on

    @property
    def is_unassigned(self):
        return self.status == TICKET_STATUS_UNASSIGNED

    @property
    def is_awaiting_handling(self):
        return self.status in [
            TICKET_STATUS_ASSIGNED,
            TICKET_STATUS_PASSED_ON,
            TICKET_STATUS_AWAITING_RESPONSE_ASSIGNEE,
        ]

    @property
    def is_in_handling(self):
        return self.status in [
            TICKET_STATUS_PICKEDUP,
            TICKET_STATUS_AWAITING_RESPONSE_USER,
        ]

    @property
    def is_handled(self):
        return self.status in [TICKET_STATUS_RESOLVED, TICKET_STATUS_CLOSED]

    @property
    def is_open(self):
        """Return True if the Ticket hasn't been resolved or closed."""
        return self.status not in [TICKET_STATUS_RESOLVED, TICKET_STATUS_CLOSED]

    @property
    def priority_level(self):
        if self.priority == TICKET_PRIORITY_URGENT:
            return 3
        elif self.priority == TICKET_PRIORITY_HIGH:
            return 2
        elif self.priority == TICKET_PRIORITY_MEDIUM:
            return 1
        else:
            return 0

    @property
    def status_classes(self):
        if self.is_unassigned:
            return {"class": "danger", "text": "white"}
        if self.is_awaiting_handling:
            return {"class": "warning", "text": "dark"}
        if self.is_in_handling:
            return {"class": "success", "text": "white"}
        if self.status == TICKET_STATUS_RESOLVED:
            return {"class": "primary", "text": "white"}
        elif self.status == TICKET_STATUS_CLOSED:
            return {"class": "secondary", "text": "dark"}


class Followup(models.Model):
    """
    Response concerning a Ticket, from either the user or handler.
    """

    ticket = models.ForeignKey(
        "helpdesk.Ticket", on_delete=models.CASCADE, related_name="followups"
    )
    text = models.TextField(blank=True, null=True)
    by = models.ForeignKey(
        "auth.User", on_delete=models.CASCADE, related_name="ticket_followups"
    )
    timestamp = models.DateTimeField()
    action = models.CharField(max_length=32, choices=TICKET_FOLLOWUP_ACTION_TYPES)

    class Meta:
        ordering = ["timestamp"]

    def __str__(self):
        return "%s, by %s on %s: %s" % (
            self.ticket,
            self.by,
            self.timestamp,
            self.get_action_display(),
        )

    def get_absolute_url(self):
        return "%s#%s" % (
            reverse("helpdesk:ticket_detail", kwargs={"pk": self.ticket.id}),
            self.id,
        )

scipost_django/edadmin/views/base.py
__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


import operator

from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, render

from guardian.shortcuts import get_objects_for_user

from colleges.permissions import is_edadmin
from submissions.models import Submission


@login_required
@user_passes_test(is_edadmin)
def edadmin(request):
    """
    Editorial administration page.
    """
    context = {"stages": Submission.STAGE_SLUGS}
    return render(request, "edadmin/edadmin.html", context)


@login_required
@user_passes_test(is_edadmin)
def _hx_submissions_in_stage(request, stage):
    """
    List Submissions in a given stage.
    """
    if stage not in Submission.STAGE_SLUGS:
        raise Http404(f"This Submission stage does not exist: {stage}")
    submissions = get_objects_for_user(request.user, "submissions.take_edadmin_actions")
    submissions = operator.attrgetter(f"in_stage_{stage}")(submissions)()
    paginator = Paginator(submissions, 16)
    page_nr = request.GET.get("page")
    page_obj = paginator.get_page(page_nr)
    count = paginator.count
    start_index = page_obj.start_index
    context = {
        "stage": stage,
        "count": count,
        "page_obj": page_obj,
        "start_index": start_index,
    }
    return render(request, "edadmin/_hx_submissions.html", context)


@login_required
@user_passes_test(is_edadmin)
def _hx_submission_details_contents(request, identifier_w_vn_nr):
    submission = get_object_or_404(
        Submission, preprint__identifier_w_vn_nr=identifier_w_vn_nr
    )
    context = {
        "submission": submission,
    }
    return render(request, "edadmin/_hx_submission_details_contents.html", context)


@login_required
@user_passes_test(is_edadmin)
def _hx_submission_tab_contents_edadmin(request, identifier_w_vn_nr):
    submission = get_object_or_404(
        Submission, preprint__identifier_w_vn_nr=identifier_w_vn_nr
    )
    context = {
        "submission": submission,
    }
    return render(request, "edadmin/_hx_submission_tab_contents_edadmin.html", context)

scipost_django/helpdesk/templates/helpdesk/_hx_ticket_search_form.html
{% load crispy_forms_tags %}

<form id="ticket-search-form"
      {% if queue %}
        hx-post="{% url 'helpdesk:_hx_ticket_search_table' queue_slug=queue.slug %}"
      {% else %}
        hx-post="{% url 'helpdesk:_hx_ticket_search_table' %}"
      {% endif %}
      hx-trigger="load, keyup delay:500ms, change delay:500ms, click from:#refresh-button"
      hx-sync="#ticket-search-form:replace"
      hx-target="#ticket-search-results"
      hx-indicator="#ticket-search-indicator">
 
  {% crispy form %}
</form>

scipost_django/helpdesk/templates/helpdesk/_ticket_for_object_link.html
{% load scipost_extras %}
<span class="float-end p-0">
  {% if user.is_superuser %}<a href="{{ object|get_admin_url }}" target="_blank" class="text-danger"><span style="font-size: 90%;" data-bs-toggle="tooltip" data-bs-html="true" title="Edit in admin (superusers only)">{% include 'bi/pencil-square.html' %}</span></a>&nbsp;{% endif %}
  {% with type_id=object|content_type_id %}
    <a href="{% url 'helpdesk:ticket_create' concerning_type_id=type_id concerning_object_id=object.id %}" target="_blank"><span style="font-size: 90%;" data-bs-toggle="tooltip" data-bs-html="true" title="Notice something wrong?<br/>Open a support ticket on this {{ object|object_name }}">{% include 'bi/sticky-fill.html' %}</span></a>
  {% endwith %}
</span>

scipost_django/helpdesk/templates/helpdesk/helpdesk.html
{% extends 'helpdesk/base.html' %}

{% load bootstrap %}

{% block breadcrumb_items %}
  {{ block.super }}
  <span class="breadcrumb-item">Helpdesk</span>
{% endblock %}


{% block pagetitle %}
  : Helpdesk
{% endblock pagetitle %}

{% block content %}

  <div class="row">
    <div class="col-12">

      <h2 class="highlight">Helpdesk</h2>
      <ul>

        {% if perms.helpdesk.add_queue %}
          <li>
            <a href="{% url 'helpdesk:queue_create' %}">Create a new Queue</a>
          </li>
        {% endif %}

        <li>
          <a href="{% url 'helpdesk:ticket_create' %}">Open a new Ticket</a>
        </li>
      </ul>

      {% if managed_queues.all|length > 0 %}
        <h3 class="highlight">Queues you can manage</h3>
        <div class="row p-2">

          {% for queue in managed_queues %}
            <div class="col-md-6 col-lg-4 mb-2">{% include 'helpdesk/queue_card.html' with queue=queue %}</div>
          {% endfor %}

        </div>
      {% endif %}

      {% if visible_queues.all|length > 0 %}
        <h3 class="highlight">Queues you can view</h3>
        <div class="row p-2">

          {% for queue in visible_queues %}
            <div class="col-md-6 col-lg-4 mb-2">{% include 'helpdesk/queue_card.html' with queue=queue %}</div>
          {% endfor %}

        </div>
      {% endif %}

      {% include "helpdesk/_ticket_search_section.html" %}

    </div>
  </div>

{% endblock content %}

scipost_django/helpdesk/templates/helpdesk/queue_detail.html
{% extends 'helpdesk/base.html' %}
{% load bootstrap %}
{% load guardian_tags %}
{% load automarkup %}
{% load crispy_forms_tags %}

{% block breadcrumb_items %}
  {{ block.super }} <span class="breadcrumb-item">Queue: {{ queue.name }}</span>
{% endblock %}

{% block pagetitle %}
  : Queue details
{% endblock pagetitle %}

{% get_obj_perms request.user for queue as "user_perms" %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <h3 class="highlight">Queue: {{ queue.name }}</h3>

      {% if queue.parent_queue %}
        <p>
          Parent: <a href="{% url 'helpdesk:queue_detail' slug=queue.parent_queue.slug %}">{{ queue.parent_queue }}</a>
        </p>
      {% endif %}

      {% if queue.sub_queues.all|length > 0 %}
        <p>
          Sub-queues:

          {% for sub in queue.sub_queues.all %}
            <a href="{% url 'helpdesk:queue_detail' slug=sub.slug %}">{{ sub }}</a>

            {% if not forloop.last %},{% endif %}

          {% endfor %}

        </p>
      {% endif %}


      {% if perms.helpdesk.add_queue or request.user in queue.managing_group.users.all %}
 
        <div class="container border border-danger p-2">
          <h4>Admin actions:</h4>

          {% if perms.helpdesk.delete_queue or "delete_queue" in user_perms %}
            <a class="btn btn-sm btn-danger"
               role="button"
               href="{% url 'helpdesk:queue_delete' slug=queue.slug %}">

              {% include 'bi/trash-fill.html' %}

            &nbsp;Delete this Queue</a>
          {% endif %}

          {% if perms.helpdesk.update_queue or "update_queue" in user_perms %}
            <a class="btn btn-sm btn-warning"
               role="button"
               href="{% url 'helpdesk:queue_update' slug=queue.slug %}">

              {% include 'bi/pencil-square.html' %}

            &nbsp;Update this Queue</a>
          {% endif %}

          {% if perms.helpdesk.add_queue or request.user in queue.managing_group.users.all %}
            <a class="btn btn-sm btn-primary"
               href="{% url 'helpdesk:queue_create' parent_slug=queue.slug %}">

              {% include 'bi/plus-square-fill.html' %}

            &nbsp;Add a sub-Queue to this Queue</a>
          {% endif %}

          <hr />

          <div class="card">
            <div class="card-header">
              Permissions on this Queue instance
              <button class="btn btn-link small"
                      data-bs-toggle="collapse"
                      data-bs-target="#permissionsCard">View/manage</button>
            </div>

            <div class="card-body collapse" id="permissionsCard">
              <strong>Note: Permissions are handled at the group level. To change managing and/or response groups, click on the <span class="bg-warning p-1">Update</span> button above.</strong>
              <br />
              <br />
 
              <h4>Managing group:</h4>
              {% get_obj_perms queue.managing_group for queue as "group_perms" %}

              <ul>
                <li>{{ queue.managing_group }}: {{ group_perms }}</li>
              </ul>

              <h4>Response groups:</h4>
              <ul>

                {% for group in queue.response_groups.all %}
                  {% get_obj_perms group for queue as "group_perms" %}
                  <li>{{ group.name }}: {{ group_perms }}</li>
                {% empty %}
                  <li>No group has permissions on this Queue</li>
                {% endfor %}

 
              </ul>
              <p>Users with permissions:</p>
              <ul>

                {% for u in users_with_perms %}
                  {% get_obj_perms u for queue as "u_perms" %}
                  <li>{{ u.first_name }} {{ u.last_name }}: {{ u_perms }}</li>
                {% empty %}
                  <li>No user has permissions on this Queue</li>
                {% endfor %}

              </ul>
            </div>
          </div>

        </div>
      {% endif %}


      <h3 class="highlight">Description</h3>
      {% automarkup queue.description %}
 
      <div class="highlight d-flex justify-content-between align-items-center px-3">
        <div class="fs-6">Tickets in this Queue</div>
        <div id="indicator-search-tickets" class="htmx-indicator">
          <button class="btn btn-warning text-white d-none d-md-block me-2"
                  type="button"
                  disabled>
            <strong>Loading...</strong>
            <div class="spinner-grow spinner-grow-sm ms-2"
                 role="status"
                 aria-hidden="true"></div>
          </button>
        </div>
      </div>

      {% include "helpdesk/_ticket_search_section.html" %}
 
    </div>
  </div>
{% endblock content %}

scipost_django/helpdesk/templates/helpdesk/ticket_card.html
{% load bootstrap %}
{% load automarkup %}
{% load scipost_extras %}
{% load guardian_tags %}

{% if ticket %}
  {% get_obj_perms request.user for ticket.queue as "user_perms" %}
{% endif %}

<div class="card">
  <div class="card-header">
    <div class="d-flex justify-content-between">
      <span>
	{{ ticket }}
	{% if ticket.concerning_object %}
	  <span>
	    <br/>Re: <a href="{{ ticket.concerning_object.get_absolute_url }}" target="_blank">{{ ticket.concerning_object }}</a>
	  </span>
	{% endif %}
      </span>
      {% with classes=ticket.status_classes %}
	<button class="btn btn-{{ classes.class }} text-{{ classes.text }}">{{ ticket.get_status_display }}</button>
      {% endwith %}
    </div>
  </div>
  <div class="card-content">
    <table class="table table-bordered">
      <tbody>
	<tr>
	  <th>Description</th>
	  <td>{% automarkup ticket.description %}</td>
	</tr>
	<tr>
	  <th>Defined on</th>
	  <td>{{ ticket.defined_on }}</td>
	</tr>
	<tr>
	  <th>Defined by</th>
	  <td>{{ ticket.defined_by.contributor.profile.get_title_display}} {{ ticket.defined_by.get_full_name}} ({{ ticket.defined_by.username }})</td>
	</tr>
	<tr>
	  <th>Priority</th>
	  <td>
	    {% for a in "x"|ljust:ticket.priority_level %}
	      {% include 'bi/exclamation-square-fill.html' %}
	    {% endfor %}
	    &nbsp;-&nbsp;{{ ticket.get_priority_display }}</td>
	</tr>
	<tr>
	  <th>Status</th>
	  <td>
	    {% with classes=ticket.status_classes %}
	      <span class="bg-{{ classes.class }} text-{{ classes.text }}">&emsp;</span>
	    {% endwith %}
	    {{ ticket.get_status_display }}
	  </td>
	</tr>
	{% if ticket.assigned_to %}
	  <tr>
	    <th>Assigned to</th>
	    <td>{{ ticket.assigned_to.get_full_name }} ({{ ticket.assigned_to.username }})</td>
	  </tr>
	{% endif %}
	<tr>
	  <th>Followups</th>
	  <td>
	    <ul class="list-unstyled">
	      {% for followup in ticket.followups.all %}
		<li>
		  <div class="card mb-1" id="{{ followup.id }}">
		    <div class="card-header">
		      {{ followup.by.get_full_name }} on {{ followup.timestamp }}
		    </div>
		    <div class="card-body">
		      {% automarkup followup.text %}
		    </div>
		  </div>
		</li>
	      {% empty %}
		<li>No followups have yet occurred</li>
	      {% endfor %}
	    </ul>
	    {% if ticket.is_open %}
      {% if 'can_manage_queue' in user_perms %}
		<a class="btn btn-sm btn-danger" role="button" href="{% url 'helpdesk:ticket_delete' pk=ticket.id %}">{% include 'bi/trash-fill.html' %}&nbsp;Delete</a>
		<a class="btn btn-sm btn-warning" role="button" href="{% url 'helpdesk:ticket_update' pk=ticket.id %}">{% include 'bi/pencil-square.html' %}&nbsp;Update</a>
		{% if not ticket.assigned_to %}
		  <a class="btn btn-sm btn-info" role="button" href="{% url 'helpdesk:ticket_assign' pk=ticket.id %}">{% include 'bi/arrow-right-circle-fill.html' %}&nbsp;Assign this ticket</a>
		{% else %}
		  <a class="btn btn-sm btn-info" role="button" href="{% url 'helpdesk:ticket_assign' pk=ticket.id %}">{% include 'bi/arrow-right-circle-fill.html' %}&nbsp;Reassign this ticket <span class="text-small text-muted">[currently: {{ ticket.assigned_to.username }}]</span></a>
		{% endif %}
		<br/><br/>
	      {% endif %}
	      <a class="btn btn-sm btn-success" role="button" href="{% url 'helpdesk:ticket_followup' pk=ticket.id %}">{% include 'bi/reply-fill.html' %}&nbsp;Reply/Followup</a>
	      <a class="btn btn-sm btn-primary" role="button" href="{% url 'helpdesk:ticket_mark_resolved' pk=ticket.id %}">{% include 'bi/check-square.html' %}&nbsp;Mark as resolved</a>
	      <a class="btn btn-sm btn-secondary" role="button" href="{% url 'helpdesk:ticket_mark_closed' pk=ticket.id %}">{% include 'bi/x-square-fill.html' %}&nbsp;Close this Ticket</a>
	    {% endif %}
	  </td>
	</tr>
      </tbody>
    </table>

  </div>
</div>